### ISSUE TITLE
伊勢原Dojoのイベントサービスのgroup_idを追加する

### ISSUE THREAD

**Issue by Yuppymam** [coderdojo-japan/coderdojo.jp#1059]
イベントが追加されたら、`group_id`を追加する🔖
（忘れないようイシューにした👍）

cc/ https://github.com/coderdojo-japan/coderdojo.jp/pull/1057

**Comment by yasulab** [comment]
こちら次のコミットで追加されたので Close しますね (๑•̀ㅂ•́)و✨
https://github.com/coderdojo-japan/coderdojo.jp/commit/dc8dfa8180a9905d4de1db4bbfa4fedb451ca52c
