### ISSUE TITLE
全国の道場のCoderDojo市川のロゴが表示されていない。 

### ISSUE THREAD

**Issue by ogom** [coderdojo-japan/coderdojo.jp#119]
logo の url にアクセスできないので、ロゴが表示されていない。
https://github.com/coderdojo-japan/coderdojo.jp/blob/master/db/dojos.yaml#L277

**Comment by yasulab** [comment]
報告ありがとうございます！😆
こちらcoderdojo.jp で画像をホストする形で解決できたので閉じちゃいますね :)
