### ISSUE TITLE
/partnership に OGP description を設定する

### ISSUE THREAD

**Issue by Yuppymam** [coderdojo-japan/coderdojo.jp#1301]
検索時の情報量を増やしたい！
<img width="791" alt="og-description-1" src="https://user-images.githubusercontent.com/48109243/124215190-83bb4980-db2e-11eb-8ae6-fa62f966293a.png">

**Comment by yasulab** [comment]
こちら費用対効果高そうだったので、早めに対応しておきました! 🛠💨✨

:octocat: 690eb80 `Fix #1301: Enable to set meta description for specific doc pages`

![image](https://user-images.githubusercontent.com/155807/128835310-3815b138-39bd-4268-9b84-adf4fe3a2552.png)

**Comment by yasulab** [comment]
LGTM 😎🆒✨

![image](https://user-images.githubusercontent.com/155807/128836830-5c311af2-7a87-4b19-9197-416267eb4051.png)
