### ISSUE TITLE
[質問]connpassで募集中のオンラインイベントの判定について

### ISSUE THREAD

**Issue by togazo** [coderdojo-japan/coderdojo.jp#1374]
<img width="488" alt="スクリーンショット 2021-08-07 21 18 35" src="https://user-images.githubusercontent.com/6989972/128599890-47aea7ad-953a-409a-87b7-d5cdfaa91b9a.png">
質問です。
当会のこの2つのイベント、フルリモートでの開催にもかかわらず「オンライン」の黄色のラベルがついていないのですが、このラベルがつくようにするためにイベント名の命名規則があるようでしたらご教示いただけますでしょうか。

**Comment by yasulab** [comment]
@togazo タイトルに `オンライン` が含まれているかどうかになります！具体的なコードはこちらです (๑•̀ㅂ•́)و✨

```haml
# 当該コード (Ruby+Haml)
if event[:event_title].include? 'オンライン'
  %div.event-ribbon
    %span オンライン
```

cf. https://note.com/yasslab/n/nde85f7850628

**Comment by togazo** [comment]
!! 記事見た覚えがありますがスッカリ忘れていました><
なるほどありがとうございます!!
