### ISSUE TITLE
『CoderDojo へようこそ! (スライド)』が閲覧できない

### ISSUE THREAD

**Issue by Reputeless** [coderdojo-japan/coderdojo.jp#1401]
https://coderdojo.jp/kata の本文中で紹介されている『CoderDojo へようこそ! (スライド)』について、
Google スライドの権限設定が公開設定ではなく、閲覧できません。

![image](https://user-images.githubusercontent.com/3108136/145169340-d771d820-0e50-4459-8714-135cfaf5d262.png)

**Comment by yasulab** [comment]
報告ありがとうございます!  6a51300 で修正しておきました! 🛠💨✨
