### ISSUE TITLE
メンテナンスページにツイッターを埋め込みたい 

### ISSUE THREAD

**Issue by rakuda-san-desu** [coderdojo-japan/coderdojo.jp#1450]
チュートリアルで行っているように、エラーページにツイッターを埋め込みたい。
（トラブルによってページの表示ができない場合に、最新情報のアナウンスがユーザーに伝わりやすい。）
例: https://railstutorial.jp/404
![スクリーンショット 2022-08-29 14 31 32](https://user-images.githubusercontent.com/41533420/187129938-2d95fcd5-f72b-4464-a0fa-55c87cba4d81.png)

**Comment by yasulab** [comment]
これはできてそうなので、一旦 Close しますね！！！
https://coderdojo.jp/404
