### ISSUE TITLE
トップページの「最近のCoder Dojo」(Twitter埋め込み)を中央寄りにする

### ISSUE THREAD

**Issue by T-taku** [coderdojo-japan/coderdojo.jp#1456]
<img width="1401" alt="image" src="https://user-images.githubusercontent.com/39856622/194344809-c7a2bf76-7e68-47d0-ab83-41b777f0e632.png">

左寄りになっていて不自然なので、中央寄りにしたほうがいいかと...👀

**Comment by Yuppymam** [comment]
#1457 にて対応しました！イシュー作成ありがとうございました😊
