### ISSUE TITLE
/docs 以下にあるページの Title を動的に切り替える仕組み作りたい

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/coderdojo.jp#146]
h1 タグの内容を持ってきて追加タイトルに入れるような仕組みがあると便利。例えば https://coderdojo.jp/docs/privacy の場合は、「プライバシーポリシー - CoderDojo Japan」になると良さそう🤔

## 他の例

- https://coderdojo.jp/docs/charter => CoderDojo 憲章 - CoderDojo Japan
- https://coderdojo.jp/docs/charter_en => CoderDojo Foundation charter for CoderDojo
 - CoderDojo Japan
- https://coderdojo.jp/docs/teikan => 一般社団法人 CoderDojo Japan 定款 - CoderDojo Japan

**Comment by yasulab** [comment]
とりあえずリリースに向けてササっと実装したんですが、雑なので誰か改善してもらえると嬉しいです 🙏  💦 
https://github.com/coderdojo-japan/coderdojo.jp/commit/ff2d2579fa6e927879491900b202e34a878596bc

**Comment by yasulab** [comment]
.oO(@nalabjp さんあたりに綺麗にしてもらえないかな) チラッ

**Comment by nalabjp** [comment]
👀

**Comment by yasulab** [comment]
すみません facebook debugger でみたらURLが反映されてなかったので雑実装が増えました... 🙇 🙇 🙇 💦

**Comment by yasulab** [comment]
切り替えるようにしたので Close します! ✅ 
https://github.com/coderdojo-japan/coderdojo.jp/pull/149
