### ISSUE TITLE
数字の表示がぶれているのを修正したい

### ISSUE THREAD

**Issue by rakuda-san-desu** [coderdojo-japan/coderdojo.jp#1507]
> 数字の部分が背景にある色（白色）とブレていてちょっと微妙な感じになっているので、よければ直してもらえると嬉しいです...!! (＞人＜ )

<img width="854" alt="3bb78fc131ee1a80a89bd6fef9b3e927" src="https://user-images.githubusercontent.com/41533420/221465680-1399647c-e4a4-46d4-9bb5-dc86e63a5c07.png">

**Comment by rakuda-san-desu** [comment]
グラフ内の数字の表示スタイルは`Highcharts`で管理されていそうです。
付与されているスタイルは下記で、白抜き風に`text-shadow`が多重でかけられているのが原因と考えます。
`text-shadow`を一つにするか、無しにして黒のテキスト表示だけにすると良さそうです。

`style="font-size:11px;font-weight:bold;color:#000000;text-shadow:1px 1px #FFFFFF, -1px -1px #FFFFFF, -1px 1px #FFFFFF, 1px -1px #FFFFFF;fill:#000000;text-rendering:geometricPrecision;"`

**Comment by Yuppymam** [comment]
いいと思います！🙆‍♀️
> 黒のテキスト表示だけにすると良さそうです👀

以下コードで確かめられました😊

```css
#dojo_tag_chart tspan {
  text-shadow: none;
}
```

<img width="646" alt="スクリーンショット 2023-02-27 13 50 50" src="https://user-images.githubusercontent.com/48109243/221477074-c5622bc5-fa4a-4c75-8f9b-5fc7cc8d6f82.png">

**Comment by rakuda-san-desu** [comment]
表示確認ありがとうございます！
すっきしますね✨
