### ISSUE TITLE
都道府県別CoderDojoカレンダーに必要な情報をEvent APIに追加する

### ISSUE THREAD

**Issue by takatama** [coderdojo-japan/coderdojo.jp#1546]
Event APIに以下の情報を追加していただくことで、都道府県別のCoderDojoカレンダーをEvent APIから作成できるようになります。

https://qiita.com/takatama/items/60276143e441c1c4f078

要望の優先度が高い順に記載します。APIの項目名はあくまで候補であり、別の項目名で全く問題ありません。

# 必須
- 終了時刻 `event_end_at`
  - カレンダーに表示する上で、終了時刻が必要です。
  - なお、開始時刻は `event_date` を参照しています。

# あると嬉しい
- 都道府県 `prefecture`
  -  Dojo APIと併用することで取得は可能ですが、Event APIに記載してあるとそのまま利用できます。
- 更新日 `event_update_at`
  - 開催予定に変更があった場合に、カレンダーを更新します。
  - なお、あわせて開催予定のID `event_id` があると、更新有無の判定がしやすくなります。ただし、`event_url`を`event_id`の代わりに使うことは可能です。
- 開催場所の住所 `address`
  - カレンダーに開催場所の位置情報として登録することで、当日の移動に利用できます。
  - 開催場所の名前 `place` もしくは `venue_name`をカレンダーに記載することで、より安心して使えるようになりそうです。
- 先の予定（例えば、2〜3カ月後の予定）
  - カレンダーの利用者が、自分の予定と見比べることができるためです。
  - Event APIがどう利用されているかが分かりませんが、もし破壊的な変更になる場合、APIの query parameter で期間を指定可能にする必要があるかもしれません。

# あっても良い
- イベントの定員 `limit`
  - 参加者数 `participants` と合わせてカレンダーに表示することで、そのイベントの様子を伺えます。

**Comment by yasulab** [comment]
要望リクエストありがとうございます! :pray: ✨

リソースが非常に限定的であるため「すぐに実装する」といった対応ができない状況で心苦しいですが、今後 API 関連で何か動く場面などあれば本フィードバックを参考にしますね! (๑•̀ㅂ•́)و✨

**Comment by takatama** [comment]
どうもありがとうございます！
ソースコードを確認して、すでにデータベースに項目があるものと、追加が必要なものを分けてみました。

- データベースに項目あり
  - event_id（connpassやDoorkeeperのevent_idではなく、upcoming_eventsテーブルのid）
  - event_end_at
  - prefecture
  - participants

- データベースの変更が必要な項目
  - event_update_at
  - address
  - place
  - limit

これを元に、events.jsonに新しく項目を追加するPRを作ってみますね！

**Comment by takatama** [comment]
#1547 でマージされました 👏
