### ISSUE TITLE
Scrivito の API Keys がなくてもローカルで立ち上げられる仕組みが欲しい

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/coderdojo.jp#156]
![scrivito error](https://user-images.githubusercontent.com/155807/31897546-ab7141e0-b851-11e7-9810-b73134b9bfe9.png)

> んん？
> CoderDojo.jp をCloneしてローカル環境で rails server しても動かない...
> と思ったら月額のサービスのAPI Keyを要求してきやがった！
> こりゃ財力も技術力も知識もない非力な中学生には無理ですわ💦
> #CoderDojo 

cf. https://twitter.com/yu_san_19/status/922469153486671872

**Comment by yasulab** [comment]
トップページでは Scrivito 使う予定はないので、Scrivito の対象スコープを Routing などで切り分けちゃうのがいいのかな 🤔 、あだ試してないですが、個人用の別の API Keys とかだとエラーになるのかなぁ💭

**Comment by hanachin** [comment]
アカウントを発行してCoderDojoのCMSの機能をユーザーとして使うことは出来ても開発自体はAPIキーがないと出来ないですね。
現状だとAPIキーを共有しないと開発出来ないので開発のしやすさではPaaSに依存しない方が便利そうです。

**Comment by yasulab** [comment]
Rails CMS を提供している背景のスライドあったので、一応載せておきます 📝 

CoderDojo を支える Rails CMS の活用事例 - Speaker Deck
https://speakerdeck.com/yasulab/coderdojo-wozhi-eru-rails-cms-falsehuo-yong-shi-li

**Comment by zephiransas** [comment]
これScrivitoのサイトにユーザ登録すると発行されるデモサイト用の```SCRIVITO_TENANT```と```SCRIVITO_API_KEY```を利用するのではダメですか 🤔 

自分も当リポジトリをcheckoutしてローカル環境を構築中ですが、上記の問題は回避できてます。
（ただその先で詰まってますが・・・ 😅

**Comment by yasulab** [comment]
> これScrivitoのサイトにユーザ登録すると発行されるデモサイト用のSCRIVITO_TENANTとSCRIVITO_API_KEYを利用するのではダメですか 🤔

@zephiransas おぉ! ちょうどこれがうまくいくのかどうか気になっていたところでした 😸 

> （ただその先で詰まってますが・・・ 😅

具体的にはどのあたりで詰まってしまう感じですか? 🤔

**Comment by zephiransas** [comment]
> 具体的にはどのあたりで詰まってしまう感じですか? 🤔

```cms_controller.rb```にて```SCRIVITO_WORKSPACE```という環境変数を参照していますが、これってなにを指定するといいでしょうか？事前にどこからかWorkspaceを作っておく必要がありますか？
（Scrivitoがあまりよくわかってないので、拙い質問で恐縮です 😓

**Comment by yasulab** [comment]
これは Git で言うところの `branch` に該当する概念ですね。

`個人アカウント has_many ワークスペース` みたいな感じの構成になっているので、とりあえず手元で適当なワークスペースを作っておいて、それを環境変数に入れておけば大丈夫だと思います ;)

```
$ rails console
> Scrivito::Workspace.create(title: "HOGEHOGE")

$ export SCRIVITO_WORKSPACE=HOGEHOGE
```

cf. https://scrivito.com/about-working-copies

**Comment by zephiransas** [comment]
上記のように```rails c```でWorkspaceを作ることで、ひとまず動作させることができました！

**Comment by yasulab** [comment]
おぉ、よかったです! 😸 でもおそらく CMS オブジェクトにアクセスできないはずなので、一部の画面表示が間違っていそうですね 💦 (やはり関係ないページは Scrivito を使わない方が良さそう🤔)

**Comment by nalabjp** [comment]
> 「もし SCRIVITO_WORKSPACE がなければ作っちゃう」という処理を入れれば

チラッとソース眺めてみた程度の知識なんですが、
`Scrivito::Workspace.find_by_title(title)`ってAPIがあるみたいなのでこの辺使うといいかもですね。

```
title ||= ENV['SCRIVITO_WORKSPACE'] || 'DEFAULT_WORKSPACE'
Scrivito::Workspace.create(title: title) unless Scrivito::Workspace.find_by_title(title)
```
って感じの実装をinitializersに足しておくといいのかな？

**Comment by yasulab** [comment]
おー！あとで試してみます！😆✨

**Comment by yasulab** [comment]
@zephiransas こちらの Issue 解決してみました! ✅ これでトップページはローカル環境でも立ち上がるようになったかなと思いますが、いかがでしょうか? ;) よければご確認していただけると嬉しいです! 😸

実装詳細: https://github.com/coderdojo-japan/coderdojo.jp/pull/162

**Comment by zephiransas** [comment]
@yasulab 
完璧です！！ 👏 
トップページが```static_pages```に切り出されて、いい感じになってますねー 👍 

#150 あたりが気になってたので、やってみようかと思います！

**Comment by yasulab** [comment]
おぉ、よかったです! ご確認ありがとうございます 😸
