### ISSUE TITLE
一部の PR では Scrivito に関するテストが落ちる問題を解決したい

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/coderdojo.jp#160]
２〜３回に１回ぐらいの確率で落ちているので、これの原因を調査したいです >< 💦 
問題が解決できると嬉しいですが、現在はそもそもの原因がわかっていない状況です🤔💭
cf. https://github.com/coderdojo-japan/coderdojo.jp/pull/159

# 追記: forked repository からの PR だと落ちるのが分かった

> https://github.com/coderdojo-japan/coderdojo.jp/pull/159#issuecomment-339517578
> 
> `SCRIVITO_TENANT`と`SCRIVITO_API_KEY`は暗号化してあるけど環境変数として使うには復号化する必要があって、それは当然ダンプ可能なのでセキュリティ的に宜しくないという理由からforkしたrepoからのジョブには渡されない仕様になっています。
> 
> ref: https://github.com/coderdojo-japan/coderdojo.jp/pull/128#issuecomment-323575408

**Comment by nalabjp** [comment]
https://github.com/coderdojo-japan/coderdojo.jp/pull/159#issuecomment-339517578

`SCRIVITO_TENANT`と`SCRIVITO_API_KEY`は暗号化してあるけど環境変数として使うには復号化する必要があって、
それは当然ダンプ可能なのでセキュリティ的に宜しくないという理由からforkしたrepoからのジョブには渡されない仕様になっています。

ref: https://github.com/coderdojo-japan/coderdojo.jp/pull/128#issuecomment-323575408

**Comment by yasulab** [comment]
あーなるほど、感覚的には2〜3回落ちるできたが、正確には fork したレポジトリからPRを送ると落ちる、が正しいということですね🤔

**Comment by yasulab** [comment]
.oO(そうするとテストケースの方を変更するのが無難かなぁ🤔)

**Comment by nalabjp** [comment]
本番用ではない環境変数で動くならなんとかなりそうですが、
動かないとなるとscrivitoの機能を使っているところをテストしているところが全く動か無さそうですねぇ。。。

**Comment by yasulab** [comment]
なるほど、そうすると先に #156 を解決してしまうことが早いかもですね🤔

**Comment by nalabjp** [comment]
そうですね、ほぼ同じ対応になるのかなという認識です

**Comment by yasulab** [comment]
MEMO MTG w/ @nalabjp 

- 必要なチェック: yaml check ぐらい
   - `[ci skip]`?
   - shell script で分岐させる?
   - Send feedbacks to Scrivito (OSS)
- フラグを持たせることはできる
- Mock で書くと解決できそう? https://scrivito.com/fe6bd882f04b03c6

**Comment by nalabjp** [comment]
ScrivitoにsignupしてCMS instanceをtrialとしてcreateすると、
そのinstance用の`SCRIVITO_TENANT`と`SCRIVITO_API_KEY`が発行されるので、
それを使ってrspecを実行することは可能だった。

ただ、おそらくworkspace上にscrivitoのObjやWidgetが無いのでScrivito::ResourceNotFoundというエラーでテストがコケる。
ここをモックで書ければテストは通せるのかもしれない。

ここからは完全に余談なんですが、
有志のコントリビューターがOSSとしてこのフローで開発するのはなかなか厳しいのでは🤔と思いました。
モックでテストを書くにしても正しい状態が分かっていないとモックが書けないわけで。。。
`SCRIVITO_TENANT`と`SCRIVITO_API_KEY`は複数発行可能なようなので、
production用のセットとtest用のセットが二種類生成できるようになっていて、
test用のキーでリクエストが来た場合はproduction用のデータのコピーを返すとか、
そういう作りになっていると良いのになー、と思いました。（ただの思いつきなのですが😅）
Scrivitoの中の人にfeedbackして、なにかしら良い解決方法が出て来るのを期待したい感じがします。

**Comment by nalabjp** [comment]
あぁ、productionのコピーだと開発ができないのか。
そもそもproductionのworkspaceにresourceを作れないとなると、
やっぱりScrivitoのresourceに依存するところはOSSとして開発するのは厳しいということになるのかもしれないですね。

**Comment by yasulab** [comment]
Scrivito を使っている部分は一部のページ (`/kata` / `/sotechsha`) だけで、そのページは Wiki として活用だけなので、そこの開発に関わることはほとんどないのかなぁと考えています🤔 基本は Wiki ページなので、コンテンツの更新がほとんどになると考えています (Wiki はコンテンツを更新するページで、Wiki そのものを開発する必要はほとんどないと考えています) が、どうですかね? 💭

**Comment by yasulab** [comment]
なのでこの Issue で伝えたい内容としては、Wiki に関するテストを修正できるようにすることと認識しています。Wiki のコンテンツは継続的に更新されますが、Wiki の開発は継続的にはされない、という認識です。(今回テストを書いてPRが通るようになったら、以後、ほとんど開発する必要はなくなる)

**Comment by yasulab** [comment]
念のため、この Issue が立てれらたキッカケを再掲しますね。この Issue の目的は「正常であれば PR 時の CI がパスするようにしたい」という認識で、「有志のコントリビューターがOSSとしてこのフローで開発したい」という点は、(少なくとも今はまだ) 議論に対象には挙がっていないという認識です。

## CoderDojo小平の情報を更新 #159

> す、すみません…「All checks have failed」と出たのですが、これ、どうすれば良いですか!?

----------

> テスト環境にScrivitoのSCRIVITO_TENANTとSCRIVITO_API_KEYが設定されていない？ためにTravisCIでの自動テストに失敗してるみたいですね
> 
> @yasulab さん待ち、かな・・・？

----------------

> CI がときどき落ちるんですよね 😅 別途原因を調査する Issue を立てておきました。 #160
> こちらは大丈夫そうなのでマージしちゃいますね 🔧 💨

**Comment by yasulab** [comment]
上でうっかり書き込んでしまいましたが「元々何をやりたかったんだっけ?」と思い返して、この Issue が立てれらたキッカケを掘り返してみました。

この Issue の目的は「正常であれば PR 時の CI がパスするようにしたい」で、「有志のコントリビューターがOSSとしてこのフローで開発したい」という点ではなかったですね 😅 

「OSSとしての開発フロー」を議論対象に含めてしまうと議論が拡散しそうなので、まずは下記の事例を解決するべく、この Issue のスコープを「正常であれば PR 時の CI がパスするようにしたい」に絞っておきたいなと考えています >< 💦 

## CoderDojo小平の情報を更新 #159

> す、すみません…「All checks have failed」と出たのですが、これ、どうすれば良いですか!?

----------

> テスト環境にScrivitoのSCRIVITO_TENANTとSCRIVITO_API_KEYが設定されていない？ためにTravisCIでの自動テストに失敗してるみたいですね
> 
> @yasulab さん待ち、かな・・・？

----------------

> CI がときどき落ちるんですよね 😅 別途原因を調査する Issue を立てておきました。 #160
> こちらは大丈夫そうなのでマージしちゃいますね 🔧 💨

--------------

> おお…とりあえずこちらが何かしでかした訳ではないなら良かったです。対応ありがとうございます！

**Comment by nalabjp** [comment]
あー、たしかに僕がコンテキストを勘違いしていたせいで話が大きくなってますね、すみません😢

**Comment by yasulab** [comment]
いえいえ! 😸 元々余談だとおっしゃっていたの対して、僕の方も話をややこしくしちゃってすみません >< 💦 今回の Issue に限れば、ナラさんが書いてくれた下記の対応で完了かなと考えています! 😆

> おそらくworkspace上にscrivitoのObjやWidgetが無いのでScrivito::ResourceNotFoundというエラーでテストがコケる。ここをモックで書ければテストは通せるのかもしれない。

**Comment by nalabjp** [comment]
ひとまずcontrollerとrequestのテストはモック化してみましたが、
http status 200だけを見ているようなテストはちょっと苦しいですね。
routingのテストをしているだけのような🤔
https://github.com/coderdojo-japan/coderdojo.jp/compare/7f337c3...6c857d9

あと、featureテストは表示される画面に依存すると思うので、
まだちょっとどうすればいいか分かっていません。
意図した画面がレンダリングされるようなmockオブジェクトをちゃんと作らないといけなさそうなのと、
ENVをつかったログインあたりはログイン処理もstubするとかも必要そうな感じですね。

**Comment by nalabjp** [comment]
https://github.com/coderdojo-japan/coderdojo.jp/pull/203#issuecomment-345542528
この観点で調査しなおします💪

**Comment by yasulab** [comment]
お願いします! 😸
