### ISSUE TITLE
モバイル版の「全国の道場」の表示方法を改善する

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/coderdojo.jp#174]
もっと良い表示方法はないかな 🤔

> はい、そんな感じですね、108道場を一所懸命にスクロールするのはちょっと疲れるというか、スマホになるともっと疲れるというかってことで勝手にです。。「調べる」っていうよりは、「表示数を減らす」って感じかもです。
> cf. https://twitter.com/yu_san_19/status/926114705298432000

-----------------------

> モバイルだと縦スクロールが長くなってしまう問題は確かになんとかできると嬉しいですね🤔
> 
> UXを改善するアプローチはいくつかあるので、次のようなUXを良くするデザインを調べておくと良いPull Requestに繋がりそうです! ;)
> https://www.webprofessional.jp/6-ways-to-improve-long-scroll-mobile-websites/

## 案1: アコーディオン by @nalabjp

> 最近はアコーディオンとか使わないんですかね？🤔 < スマホUI
> 地方ごとに折りたためるとスクロール幅が減らせそうに思いました。

あー、なるほど。スマホ版はデフォルトを折りたたんでおくという手は面白そうですね🤔 `dojos.yml` の名前欄にある地域名を `region` みたいな項目 (近畿、四国など) に移して、`region`ごとに折りたたんで表示するというアイデアは面白そうです! 😸

**Comment by zephiransas** [comment]
まずはアコーディオンにするのが良さそうですねー 👍
