### ISSUE TITLE
Dojoのイベント数を定期的に更新する

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/coderdojo.jp#184]
- 定期的にRakeタスクを実行する #12
- Cron には Heroku Scheduler を使用する
- 更新した値をトップページで表示する

**Comment by nalabjp** [comment]
#182 #183 を取り込んだので、一度過去分全てを集計するrake taskを実行して、
こちらを設定してもらうと良さそうです。

`bundle exec rails statistice:aggregation\[2012\]` で2012から前月まで全てが集計されます。（実行時間はローカルだと22分ぐらいでした）

**Comment by yasulab** [comment]
> `bundle exec rails statistics:aggregation\[2012\]` で2012から前月まで全てが集計されます。（実行時間はローカルだと22分ぐらいでした）

手順の説明ありがとうございます! そろそろ移動しようと思ってたので、移動先で試してみますね 😸

**Comment by nalabjp** [comment]
> 一度過去分全てを集計するrake taskを実行

ここまでHeroku上で実行済みです。
定期実行の設定をしようとHeroku Schedulerのアドオンをインストールしたけど、
月1回とか週一回なんて選択肢がなかったですね。（イマココ、さてどうしよう🤔）

**Comment by nalabjp** [comment]
> 月1回とか週一回なんて選択肢がなかった
`[ $(date +%d) = 01 ] && bundle exec rails statistics:aggregation` を設定しました。

**Comment by yasulab** [comment]
設定ありがとうございます! 😸 これで毎月実行できそうですね ;) 

ちなみに `[ $(date +%u) = 1 ] && bundle exec rails statistics:aggregation` のように毎週実行する場合は、統計スクリプトの方を変更する必要がある、という認識で大丈夫でしょうか? 🤔

**Comment by nalabjp** [comment]
そうですね、APIを叩く時のパラメータで年月による絞り込みを行っているので、
絞り込み範囲を変える必要があります。
connpassだけ範囲指定ではなく、年月日の複数指定にする調整も必要そうですね。

cf: https://connpass.com/about/api/

**Comment by yasulab** [comment]
ありがとうございます! 実行間隔についてはおいおい対応するぐらいにして、こちらの Issue については一旦閉じちゃいますね ;)

対応ありがとうございました! 😸
