### ISSUE TITLE
CmsControllerが必要

### ISSUE THREAD

**Issue by hanachin** [coderdojo-japan/coderdojo.jp#187]
> RuntimeError (Your application does not define the "CmsController" needed for Scrivito. Did you forget to run "rails generate scrivito:install"?):

**Comment by yasulab** [comment]
> CmsController必須なんじゃないですかね

あー、今ドキュメント見たら必須っぽい気がする。この前 Rename するコミットをし他ので、それを Revert するだけで良いはずなので、僕の方で修正しときますね :wrench: :dash: :sweat_drops: 
https://scrivito.com/scrivito-sdk

cf. 76d3532e0852abdc23049c79fb8714d446a6c6ba

**Comment by yasulab** [comment]
> CmsController必須なんじゃないですかね

あー、今ドキュメント見たら必須っぽい気がする... 😓 

>  If this controller is missing, it falls back to CmsController, the superclass of all controllers that can handle CMS object requests.

Scrivito SDK
https://scrivito.com/scrivito-sdk

この前 Rename するコミットをしたので、それを Revert するだけで良さそうかな🤔💭 僕の方で修正しときますね :wrench: :dash: :sweat_drops: 


cf. 76d3532e0852abdc23049c79fb8714d446a6c6ba

**Comment by yasulab** [comment]
Thanks for your report! 😸 Fixed by this commit: https://github.com/coderdojo-japan/coderdojo.jp/commit/7c1b1e78bd32a1db0c889772bd6534b49986f107 ✅
