### ISSUE TITLE
Dojo一覧の並び順が分かり辛い

### ISSUE THREAD

**Issue by nalabjp** [coderdojo-japan/coderdojo.jp#201]
https://github.com/coderdojo-japan/coderdojo.jp/pull/188#issuecomment-344918873

> すみません。あまり技術的なこととは関係がないのですが…これ、なんで中部が関東より先なんでしょう…いえ、なんとなく政府が出している統計データなども踏まえて一般的に北海道・東北・関東・中部…の順では…というところで、関東と中部の情報を見ようとして上下逆で迷子になりまして…

https://github.com/coderdojo-japan/coderdojo.jp/pull/188#issuecomment-345283526
> お、たぶん僕が適当に並べちゃっていて、 zephiransas さんはそれに合わせていただいた感じですね 😅

直接的な原因は[ここ](https://github.com/coderdojo-japan/coderdojo.jp/blob/a75d348bbf4ef5fcee9766b37801325afda9e9f7/app/models/dojo.rb#L12)でdefault_scropeとしてorderが定義されているので、
[一覧表示用に取得したDojo](https://github.com/coderdojo-japan/coderdojo.jp/blob/a75d348bbf4ef5fcee9766b37801325afda9e9f7/app/controllers/static_pages_controller.rb#L4)が今の並び順になっていますね。

一般的な並びに直したほうが良さそうですかね。
prefecture_id順にDojoを持ってくるようにすれば直りそうです。
default_scopeはあまり使わないほうがいいので、それも併せて直せると良いかもしれません。

**Comment by nalabjp** [comment]
> prefecture_id順にDojoを持ってくるようにすれば直りそうです。

これで実装すると`Dojo#order`が不要になりそうな気がするんですが、
dojos.yamlにも書かれている値で順序の意図があるといけないので、
念のため確認をお願いします。 > @yasulab 
意図して並び替えをしたいケースが残っているようなら、
prefecture_id順でregionごとにgroup byしたあとで適用する（region内で並び替える）とかにする感じでしょうかね🤔

**Comment by yasulab** [comment]
> dojos.yamlにも書かれている値で順序の意図があるといけないので、
> 念のため確認をお願いします。 > @yasulab

@nalabjp 順序に意図は特になくて、 https://github.com/coderdojo-japan/coderdojo.jp/issues/58 の Issue があげられた段階から「いつかちゃんと直さないとなぁ🤔」という感じですね 😸 

> prefecture_id順でregionごとにgroup byしたあとで適用する（region内で並び替える）とかにする感じでしょうかね🤔

はい! 地方の表示順に関してはそちらで良いと思います ;) 

もし良い解決策があれば dojos.yaml の `order` を削除して、CoderDojo の表示順序を自動ソートもできるようになる ( #58 ) と良いかなと考えていますが、とりあえず自動ソートについては後回しでも良いかもしれませんね 💭

**Comment by nalabjp** [comment]
そういえば #58 ありましたね、忘れていました。
#58 は仕様が決まりきっていないように見えるので、
ひとまず地方順だけ対応しておきましょうかね。

**Comment by yasulab** [comment]
@nalabjp あ、今気づいたんですが、第２ソートキーって現在だと `id` になってるんでしたっけ? 🤔

現在の https://coderdojo.jp/#dojos の順序だと「札幌」と「札幌東」の間に「恵庭」が入っていて、少し違和感があります。「北海道」でソートした後に `order` あたりでソートするといいのかなぁと考えています 💭 

<img width="742" alt="screen shot 2017-11-26 at 23 58 53" src="https://user-images.githubusercontent.com/155807/33241239-192384ae-d306-11e7-94e0-5a3b68861c04.png">

cf. https://github.com/coderdojo-japan/coderdojo.jp/issues/219

**Comment by nalabjp** [comment]
> 「札幌」と「札幌東」の間に「恵庭」が入っていて

prefecture_idで並べ替えた時に変わってしまっていたみたいですね😣
#217 で第二ソートキーをidにしましたが、orderを第二ソートキーにすべきなんですかね🤔

**Comment by yasulab** [comment]
> #217 で第二ソートキーをidにしましたが、orderを第二ソートキーにすべきなんですかね🤔

order はできればいつか削除したいなぁと考えていますが ( #58 )、現状だと第二ソートキーして使えそうなのは `order` だけなので、 #58 が解決されるまでは order を第二ソートキーにすると良いかなと考えています ;)

なので暫定的な処置として `order` を第二ソートキーとして使ってもらえると嬉しいです!  🙏
