### ISSUE TITLE
CoderDojo の表示順序を決定しているorderを自動更新したい

### ISSUE THREAD

**Issue by nalabjp** [coderdojo-japan/coderdojo.jp#228]
https://github.com/coderdojo-japan/coderdojo.jp/issues/58#issuecomment-350717763

> 全国地方公共団体コードを Google Spreadsheet に載せたので、いずれは表を lookup して自動で order の値を見つけられるようにしたいなと考えています 🤖💨

ref:
[全国地方公共団体コードを Google Spreadsheet に載せた](https://docs.google.com/spreadsheets/d/1b2XZxifpP8GSASvP9sPq1BYwsCH6Y_FHSkol_nfaGxw/edit#gid=1813423171)

**Comment by yasulab** [comment]
> RubyからGoogleSpredSheetにアクセスする場合別途jsonファイルが必要である事から、ローカル環境でアクセスしてorderを見つけるのが良いかと考えました。

確かに...!! 👍 ✨ ローカル環境で処理できた方が開発も楽そう ;) CSV 形式にしてローカルにコミットすると良さそうなのかな🤔💭

**Comment by AnaTofuZ** [comment]
なるほど! ローカルでGoogleスプレッドシートにアクセスするだけになるかな…とか考えていてcsvを落とすことを考えてませんでしたΣ(ﾟДﾟ)

今のp-rではリモートアクセスで書いていたのでcsvを入れる方向性の方が良さそうですね(jsonの取扱が懸念点だったので)
