### ISSUE TITLE
原因調査: SSL周りでアクセスできないことがある?

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/coderdojo.jp#253]
- [Heroku ACM](https://qiita.com/yasulab/items/792dc0048bbd0b5ca96e) が原因?
- Let's Encrypt で自動更新すれば解決する?
- 原因は判明していないが、Webサイトにアクセスできなくなるのは困るので、原因を調査したい

## 成功時
![default](https://user-images.githubusercontent.com/155807/35895112-5fada478-0bf9-11e8-94a1-17cb5521dcc1.png)

## 失敗時
![default](https://user-images.githubusercontent.com/155807/35895111-5f8a0f2c-0bf9-11e8-9764-1b8e62f4b8fc.png)
![yasslab](https://user-images.githubusercontent.com/155807/35895110-5f625586-0bf9-11e8-81ec-9963cdc0a194.png)

**Comment by yasulab** [comment]
こちらの件、Heroku に直接問い合わせるといいんじゃないかと思いつき、問い合わせフォームよりコンタクトを取ってみました ;) 📨 💨 

# Heroku ACM seems to not use Let's Encrypt occasionally.

Hi, my company (YassLab) provides two websites by Heroku ACM, CoderDojo Japan and YassLab website. We provide other websites in the same way and they work perfect, but the two websites are occasionally failed to access because of SSL. Well, how can we fix this SSL problem?

I have attached the screenshots when succeeded and when failed for both. Hope these helpful for digging into the problem.

## CoderDojo Japan https://coderdojo.jp

### Failed
![coderdojo-fail.png](https://heroku-support-production.s3.amazonaws.com/ca0080e1-7c6a-4b1c-82a4-483c6cadf97e%2Fd2e0c641-53ac-4c09-a4a1-6d9f0c7c86d8%2Fcoderdojo-fail.png)

### Success
![coderdojo-success.png](https://heroku-support-production.s3.amazonaws.com/ca0080e1-7c6a-4b1c-82a4-483c6cadf97e%2Fd2e0c641-53ac-4c09-a4a1-6d9f0c7c86d8%2Fcoderdojo-success.png)

## YassLab https://yasslab.jp/

### Failed
![yasslab-fail.png](https://heroku-support-production.s3.amazonaws.com/ca0080e1-7c6a-4b1c-82a4-483c6cadf97e%2Fd2e0c641-53ac-4c09-a4a1-6d9f0c7c86d8%2Fyasslab-fail.png)

### Success
![yasslab-success.png](https://heroku-support-production.s3.amazonaws.com/ca0080e1-7c6a-4b1c-82a4-483c6cadf97e%2Fd2e0c641-53ac-4c09-a4a1-6d9f0c7c86d8%2Fyasslab-success.png)

Thanks,
Yohei Yasukawa
yohei@yasslab.jp

**Comment by yasulab** [comment]
回答が来ました! DNS 側の問題っぽいので、Gehirn DNS に問い合わせして来ます 📨 💦 

# Heroku's Answer

Hi there,

This is due to the DNS records your domains are using. For example when looking at coderdojo.jp I get the following records:

```
$ dig +noall +answer coderdojo.jp
coderdojo.jp.		1	IN	A	54.225.130.23
coderdojo.jp.		1	IN	A	54.225.152.117
coderdojo.jp.		1	IN	A	54.225.199.17
coderdojo.jp.		1	IN	A	54.243.32.119
coderdojo.jp.		1	IN	A	54.243.115.172
coderdojo.jp.		1	IN	A	54.243.122.29
coderdojo.jp.		1	IN	A	54.243.147.114
coderdojo.jp.		1	IN	A	54.243.171.148
coderdojo.jp.		1	IN	A	54.243.175.5
coderdojo.jp.		1	IN	A	54.243.175.62
coderdojo.jp.		1	IN	A	54.243.194.73
coderdojo.jp.		1	IN	A	54.243.202.193
coderdojo.jp.		1	IN	A	23.21.74.117
coderdojo.jp.		1	IN	A	23.23.136.1
coderdojo.jp.		1	IN	A	54.221.226.80
```

If you are using an ALIAS or ANAME (which is what we recommend) record you domain should only be using the DNS records for the coderdojo.jp.herokudns.com DNS target:

```
$ dig +noall +answer coderdojo.jp.herokudns.com
coderdojo.jp.herokudns.com. 60	IN	A	50.16.250.54
coderdojo.jp.herokudns.com. 60	IN	A	50.19.121.155
coderdojo.jp.herokudns.com. 60	IN	A	54.204.47.4
coderdojo.jp.herokudns.com. 60	IN	A	54.221.212.171
coderdojo.jp.herokudns.com. 60	IN	A	54.225.179.161
coderdojo.jp.herokudns.com. 60	IN	A	23.23.207.44
coderdojo.jp.herokudns.com. 60	IN	A	50.16.227.190
coderdojo.jp.herokudns.com. 60	IN	A	50.16.237.173
```

You have twice as many A records as you should. I would say you are getting the non-Let's Encrypt certficate when one of the A records is used which shouldn't be there.

Cheers,
Keith

**Comment by yasulab** [comment]
Gehirn DNS にも問い合わせして来ました 📨 💨 

## エイリアス参照先にないAレコードがあるために SSL で失敗してしまう

初めまして! coderdojo.jp や yasslab.jp で Gehirn DNS を使っているのですが、エイリアス参照先にない A レコードが使われいるようで、Heroku 側で提供していないAレコードを参照した際に SSL の認証に失敗する (ページにアクセスできなくなる) ようになっております。

```
# Gehirn DNS 側の設定
Name: coderdojo.jp.
Alias: ON
エイリアス参照先：coderdojo.jp.herokudns.com.
```

Heroku 側に問い合わせたところ、「Heroku が提供していない A レコードが DNS によって設定されているため、そこで SSL (Let's Encrypt) に失敗しているだろう」との回答を受けましたが、Gehirn DNS で確認してみたところ、上記の通りエイリアス参照先は１つしか設定しておりませんでした。

こちら、もし解決方法をご存知であればアドバイスをいただけると大変幸いです。

**Comment by yasulab** [comment]
返信が返ってきました! 調査していただけるとのことです ;)

> 安川 要平さま
> 
> ゲヒルンサポートセンターです。
> 平素より Gehirn DNS をご利用くださいまして誠にありがとうございます。
> また、このたびはご不便をお掛けしておりますことをお詫び申し上げます。
> 
> エイリアス先に存在しない値が返却されているということで、当社で調査させていただきます。なお、ご不便をお掛けしておりますところ大変恐れ入りますが、調査が完了するまで Gehirn DNS の当該ゾーンやバージョンを操作することをお控えくださいますようお願い申し上げます。
> 
> 調査が完了し次第、お客様に改めてご連絡致します。
> 何卒宜しくお願い申し上げます。
> ゲヒルンサポートセンター

**Comment by yasulab** [comment]
30分で解決! Twitter が一瞬荒れかけましたが、個別に僕の方で対応しておきました 😅 

多分この Issue を解決するために一瞬落としたのかなと認識しています...? 🤔(が、落とすなら事前に連絡して欲しかった >< 💦 )

@nalabjp さんの環境ではどうでしょう? 同じ現象って発生してますかね? 👀

**Comment by nalabjp** [comment]
@yasulab 
全サイト確認しましたが問題なさそうです！👌

**Comment by yasulab** [comment]
お、良かったです! 😸 各種サイトが30分落ちるとヤバいという知見が得られました... 😅

**Comment by yasulab** [comment]
この Issue のタイトルも解決できていることが確認できたので、Issue は閉じちゃいますね! 😉 以後は SSL で失敗することはなさそうです! 😸 

## Before

```bash
╭─○ yasulab ‹2.5.0› ~
╰─○ dig +noall +answer coderdojo.jp
coderdojo.jp.		1	IN	A	23.21.92.233
coderdojo.jp.		1	IN	A	50.16.250.54
coderdojo.jp.		1	IN	A	54.204.47.4
coderdojo.jp.		1	IN	A	54.243.147.114
coderdojo.jp.		1	IN	A	50.16.227.190
coderdojo.jp.		1	IN	A	54.243.171.148
coderdojo.jp.		1	IN	A	54.243.115.172
coderdojo.jp.		1	IN	A	54.243.202.193
coderdojo.jp.		1	IN	A	50.16.237.173
coderdojo.jp.		1	IN	A	54.243.175.62
coderdojo.jp.		1	IN	A	54.243.122.29
coderdojo.jp.		1	IN	A	54.221.212.171
coderdojo.jp.		1	IN	A	50.19.121.155
coderdojo.jp.		1	IN	A	23.23.207.44
coderdojo.jp.		1	IN	A	54.243.175.5
coderdojo.jp.		1	IN	A	54.243.194.73
```

## After

```bash
╭─○ yasulab ‹2.5.0› ~
╰─○ dig +noall +answer coderdojo.jp
coderdojo.jp.		1	IN	A	184.73.200.185
coderdojo.jp.		1	IN	A	50.17.234.140
coderdojo.jp.		1	IN	A	23.23.215.144
coderdojo.jp.		1	IN	A	23.23.171.5
coderdojo.jp.		1	IN	A	23.21.55.239
coderdojo.jp.		1	IN	A	23.23.138.216
coderdojo.jp.		1	IN	A	174.129.203.239
coderdojo.jp.		1	IN	A	204.236.236.192
```

**Comment by yasulab** [comment]
> 各種サイトが30分落ちるとヤバいという知見が得られました... 😅

公式発表されてた 📜 👀 

［DNS］エイリアスを有効にしているゾーンのレコードが解決できない障害（復旧済）
https://www.gehirnstatus.jp/post/170830097216/dns%E3%82%A8%E3%82%A4%E3%83%AA%E3%82%A2%E3%82%B9%E3%82%92%E6%9C%89%E5%8A%B9%E3%81%AB%E3%81%97%E3%81%A6%E3%81%84%E3%82%8B%E3%82%BE%E3%83%BC%E3%83%B3%E3%81%AE%E3%83%AC%E3%82%B3%E3%83%BC%E3%83%89%E3%81%8C%E8%A7%A3%E6%B1%BA%E3%81%A7%E3%81%8D%E3%81%AA%E3%81%84%E9%9A%9C%E5%AE%B3%E5%BE%A9%E6%97%A7%E6%B8%88

**Comment by yasulab** [comment]
公式からのメールも来てた! 📨✨ 

> ゲヒルンサポートセンターです。
> 
> 本日発生いたしました障害につきまして原因の調査および復旧作業を含めた対応が完了いたしました事をご報告いたします。
> 
> 障害原因および復旧までの作業内容について Gehirn Web Services Status Page にてご説明しております。
> https://www.gehirnstatus.jp/post/170830097216/
> 
> また、本日午前に安川さまがご報告くださいましたエイリアス機能で存在しないAレコードが応答される問題も併せて修正いたしました。

**Comment by nalabjp** [comment]
ゲヒルンDNS側のバグだったってことなのか、なるほどー。
