### ISSUE TITLE
直近の CoderDojo 開催情報を表示したい

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/coderdojo.jp#258]
## ストーリー

1. CoderDojo を立ち上げるため、まずはどこかの Dojo を見学したい 🏃💨
2. 近日中に開催される Dojo があれば知りたいが、トップページから全部辿るのは辛い 🔍💦 
3. UI/UX などのデザインはさておき、近日中に近隣で開催される Dojo 情報がわかると嬉しい 😸 ✨ 

### 例えば「こういうとき」に便利

[![image](https://user-images.githubusercontent.com/155807/48127383-ed73ee80-e2c6-11e8-989d-d100f9fe3f5e.png)](https://www.facebook.com/groups/coderdojo.jp/permalink/1908866139226776/)

cf. https://www.facebook.com/groups/coderdojo.jp/permalink/1908866139226776/

## やりたいこと

`/events` ページで今後開催されるイベント情報を表示したい。当該ページでは次の情報を参照できる:

- これから開催される Dojo 情報のみを表示
- 遠い Dojo 情報を知っても見学できないので、できれば都道府県ごとに表示できると良い
- ユーザーは、近隣の Dojo 情報を参照し、都合の良い日に見学申請を申し出る
- cf. 統計情報ページ: https://coderdojo.jp/stats

## やらないこと
- デザインや UI/UX などは今は深く考えない。まずは情報が参照できれば十分 🙆‍♂️ 
- トップページからリンクは貼らない。まずは内部向けで十分 🙆

**Comment by AnaTofuZ** [comment]
着手しようと考えています。
実装に関して今現在の考えは

- `/events` では `/stats` の全国の道場の一覧を簡易化したものを表示する
- 近日開催の`Dojo` 情報は `dojo_event_services` か `envent_histories` あたりから引っ張りたい

などです。`/stats` のControllerを読んで実装したいと思っていあmす。

**Comment by AnaTofuZ** [comment]
`EventHistory.where(evented_at:Time.zone.now..Time.zone.now.end_of_year)` で取れるかな…などと思ったのですが `EventHistory` は historyだけあって過去ログしか入っていない為この方法はNGでした

**Comment by AnaTofuZ** [comment]
` DojoEventService.where(created_at: Time.zone.now..Time.zone.now.end_of_year)` 　あたりでも取れなかった。ローカル環境の問題…? 🤔

**Comment by AnaTofuZ** [comment]
一旦　herokuにアクセスしてdbの中身を見る作戦

**Comment by AnaTofuZ** [comment]
統計データの集計で使っている　`lib/statistics/aggregation.rb` を利用して集計を取るのが良さそうな気がしてきましたが、中身をまだ読み込んでないので読んでいきます

**Comment by AnaTofuZ** [comment]
`be rails r 'puts ActiveSupport::Dependencies.autoload_paths'` したところ、 `lib` 以下にはpathが通っていなかった為、Controllerから　`lib/statistics/aggregation.rb` は読めそうになかった

**Comment by AnaTofuZ** [comment]
#276 で切り出しを行ったAPIアクセスライブラリを利用して3週間あたりを目処に開催情報を取得するTaskを作成し、その結果を `recent_events` などの名前のテーブルに格納し、出力していきたいとおもっています

**Comment by AnaTofuZ** [comment]
## 格納先について

- `event_histories` とほぼ同じ構成
- 格納するtaskを `statistics` と別にする
- 3週間ごとに新しいデータを持ってくるようにcron可能なtaskを書く

**Comment by AnaTofuZ** [comment]
[Postico](https://eggerapps.at/postico/) を落としローカルのDB構成を確認

**Comment by AnaTofuZ** [comment]
## TODO
- [ ] `recently_events` モデルの作成
- [ ] 直近イベント情報の追加を行うtaskの作成
- [ ] 直近イベント情報の削除を行うtaskの作成
- [  ] `/events` 用のコントローラーを定義
- [ ] viewを作成

### 作成するtaskについて
- [ ] FaceBook
- [ ] Connpass
- [ ] dorrkeeper

**Comment by yasulab** [comment]
Fixed by #375 ✅ Thanks...!! 😻✨
