### ISSUE TITLE
CoderDojo 鳥取からの coderdojo.jp 掲載依頼に対応する過程で、ドキュメントを整備したい

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/coderdojo.jp#259]
CoderDojo 鳥取から coderdojo.jp への掲載依頼が来たので、これに対応したい。(申請内容は別途共有)

対応例: https://github.com/coderdojo-japan/coderdojo.jp/commit/cf2d579ec961f2690f2a32220e0f8b17113412f0

cf. [作業メモの例 - OSS Gate](https://www.youtube.com/watch?v=kwQ9ZzslxxA&index=7&list=PLg41HKRyxE6gIvt3sM09REYvLYkRRkuaS)

## チェックリスト

- [x] Ruby/Rails の環境構築はできた?
   - Hint: トップページの表示には環境変数は不要 (なはず)
- [x] db/dojos.yaml に Dojo 情報を追記した?
   - Hint: `be rails dojos:update_db_by_yaml`
- [x] DBからIDを取得して db/dojos.yaml に追記した?
   - Hint: `be rails dojos:migrate_adding_id_to_yaml`
- [x] ローカル環境で Dojo が表示できた?
- [x] 統計情報にイベント管理サービスを登録したか?
- [x] 本番環境に反映されたか?
- [x] 上記の作業ログをドキュメントにまとめた?

## 作業の完了条件

- [x] CoderDojo 鳥取が coderdojo.jp に掲載されている
- [x] 依頼されたロゴが表示されている
- [ ] 掲載しているロゴは TinyPNG などで画像圧縮されている
- [x] リンク先が適切である
- [x] 集計対象にも登録されている (毎週月曜日に統計情報が更新される)

**Comment by AnaTofuZ** [comment]
作業ログ

- リポジトリをfork (念のため?) 
- `bundle install --without production`
- `be rails db:migrate` 
- `be rails db:seed`

**Comment by AnaTofuZ** [comment]
- `be rspec spec/` すると

```
...FF...F1st Try error in ./spec/features/sotechsha_spec.rb:7:

          Missing the required configuration key "tenant".

          You need to configure the "tenant" and the "api_key" in order to connect the application
          to the Scrivito backend.

          Either use the environment variables "SCRIVITO_TENANT" and "SCRIVITO_API_KEY" or set the
          keys in an initializer:

            Scrivito.configure do |config|
              config.tenant  = 'my_tenant'
              config.api_key = 'secret123'
            end

          The values of the keys can be obtained from the dashboard at https://scrivito.com.
```

などと怒られる。見たところ　環境変数 `SCRIVITO_TENANT` が無いと言われていて
これは `config/initializers/scrivito.rb`  で定義されている

**Comment by AnaTofuZ** [comment]
`be rspec spec/`
テストが通る

追記したいので現在のDojoの数を確認
- `be rails console`
- `pry(main)> Dojo.count` --> 123らしい
従って鳥取は124番目のDojoとしてyamlに記述する

**Comment by AnaTofuZ** [comment]
みたところ　Dojoのidは実は考えなくてよく
`dojo.rake`に

```
    dojos.each do |dojo|
      d = Dojo.find_or_initialize_by(id: dojo['id'])
```

と書かれていて、なんとidが無いと自動でinitalizeされるのであった

**Comment by AnaTofuZ** [comment]
`Dojo` の `order` フィールドは 全国地方公共団体コードの値が入っている ( #219 )
[全国地方公共団体コード一覧表 - Google Spreadsheet](https://docs.google.com/spreadsheets/d/1b2XZxifpP8GSASvP9sPq1BYwsCH6Y_FHSkol_nfaGxw/edit?usp=sharing) から　フィールドを取ってくる

スプレッドシートの情報と照らし合わせてyamlを追加する
```
- id: 124
  order: '312011'
  name: 鳥取
  prefecture_id: 31
  logo: "/img/docs/tottori.png"
  url: "https://www.facebook.com/events/162413071215576/"
  description: 鳥取県鳥取市で毎月開催
  tags:
  - Scratch
  - Ruby
```

またリンク先からDojoの画像をダウンロードし、所定の名前で　`public/img/dojos` に配置する。
yaml情報からデータを追加
`be rails dojos:update_db_by_yaml`

**Comment by AnaTofuZ** [comment]
`created_at` が正常にyamlに吐き出されていない為、今日の日付を記述し
念のため　`be rails dojos:update_db_by_yaml` 及び　`be rails dojos:migrate_adding_id_to_yaml` を行う。

sqliteを確認したところ `created_at` は当初raikeを起動した際に入ったと思われる`2018-02-23 08:35:45.586225`タイムスタンプが記録されている。

**Comment by AnaTofuZ** [comment]
ローカルで起動した所鳥取が2つ表示される状態になっていた。db操作が原因と思われるので
`be rails db:migrate:reset`  `bin/setup` しもう一度yamlから読ませる

また画像のリンク先をtypoしていたので修正した。
この状態で先程のrakeを2回実行し、ローカルで起動した所鳥取が表示された。
![screen shot 2018-02-23 at 18 07 52](https://user-images.githubusercontent.com/13062611/36586289-8d62e91e-18c4-11e8-971f-95b84ca64144.jpg)

画像が寄っていたのでcropして修正

![screen shot 2018-02-23 at 18 09 45](https://user-images.githubusercontent.com/13062611/36586343-c16e1454-18c4-11e8-83bf-79d51d35ee2b.jpg)

**Comment by yasulab** [comment]
> 画像が寄っていたのでcropして修正

👍 ✨

**Comment by AnaTofuZ** [comment]
ありがとうございます!!

**Comment by AnaTofuZ** [comment]
見たところ鳥取はすでに次回のイベントがあるので
`db/dojos.yaml` に次回のイベント情報を追加し
`be rails dojo_event_services:upsert` 　した

**Comment by AnaTofuZ** [comment]
`集計対象にも登録` なんですが、これはイベント情報をyamlに追加する以外に何か必要なのでしょうか? 🤔

**Comment by yasulab** [comment]
イベント管理サービスを `db/dojo_event_services.yaml` に追加する作業ですね ;)
Rakeタスクの `dojo_event_services:upsert` 周りに詳しい実装があります 📜👀

**Comment by AnaTofuZ** [comment]
ありがとうございます!! 読んでみます

**Comment by yasulab** [comment]
コミット例: https://github.com/coderdojo-japan/coderdojo.jp/commit/52be3a2bb1d592fb0cc992a516957aecd92e0ed1

**Comment by AnaTofuZ** [comment]
あ、yamlファイルが違った…!!

**Comment by AnaTofuZ** [comment]
書き方(最後のfacebookURLが異なっていたので修正して再コミットしました)

**Comment by yasulab** [comment]
現在は Facebook / Doorkeeper / connpass の３つに対応していて、このいずれかの場合は自動集計ができるようになっています 🔧🤖💨 (スライド資料: https://speakerdeck.com/yasulab/coderdojo-japan-2018?slide=69 )

また、現状では人的リソースが足りないのであまり積極的に対応する必要はないのですが、Static に EventHistory を追加するインターフェイスもこちらに用意されています ;)
https://github.com/coderdojo-japan/coderdojo.jp/issues/190

**Comment by yasulab** [comment]
.oO(下書きの段階から `[WIP] hogehoge` みたいなタイトルで PR を雑に作って、その branch 上で作業するとコードが共有できるので、WIP の段階からPRを出す習慣は身につけておくと良さそうです...!!)

例: https://github.com/coderdojo-japan/coderdojo.jp/pull/252

cf. How to write the perfect pull request - GitHub
https://github.com/blog/1943-how-to-write-the-perfect-pull-request

> Be explicit about when you want feedback, if the Pull Request is work in progress, say so. A prefix of “[WIP]” in the title is a simple, common pattern to indicate that state.

**Comment by AnaTofuZ** [comment]
ありがとうございます!! 
#12 #190 を見ているのですが,Facebookの `group_id` がどこから引けるか良く解ってないです。

PRを出す習慣忘れていました。(｀；ω；´)　PRベースでやっていきます!

**Comment by yasulab** [comment]
> Facebookの group_id がどこから引けるか良く解ってないです。

`[facebook id seach]` 検索 (ポチッ

**Comment by AnaTofuZ** [comment]
ググり力が足りてなかった…! ありがとうございます!!

**Comment by AnaTofuZ** [comment]
作業は #261 で解決しました。ドキュメントの整備を行います

**Comment by yasulab** [comment]
お願いします! 😸 🙏
