### ISSUE TITLE
StaticPagesCotrollerをRESTに寄せたい

### ISSUE THREAD

**Issue by nalabjp** [coderdojo-japan/coderdojo.jp#275]
static_pages#home -> home#show
static_pages#stats -> stats#show
static_pages#letsencrypt -> letsencrypt#show
で良さそうに思います。

**Comment by yasulab** [comment]
> static_pages#stats -> stats#show

お、特に stats controller はたしかに今後拡張していく可能性がありそうですね🤔💭

**Comment by nalabjp** [comment]
はい、statsなんかは増えていきそうですし、
RESTで表現できない規模でも全然無いので今のうちにリファクタリングしてしまって良いんじゃないかと思いました。

**Comment by yasulab** [comment]
ですね! 良いと思います 😊✨
