### ISSUE TITLE
📨ニュース購読フォームをトップページに置きたい

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/coderdojo.jp#280]
@AnaTofuZ CoderDojo のニュース購読フォームを用意したので、これをトップページに埋め込む作業をお願いできると嬉しいです 🙏💦 

cf. [埋め込みコード](https://gist.github.com/tkc49/f31698fb1bfe868069c284087bc1057e)

## 参考: [Railsチュートリアルの購読フォーム](https://railstutorial.jp/#news)

![railstutorial_news_form](https://user-images.githubusercontent.com/155807/37328912-1a4e3522-26df-11e8-8584-71ea1e8f0244.png)

**Comment by AnaTofuZ** [comment]
@yasulab cfのフォームを埋め込む感じですね! やってみます

**Comment by yasulab** [comment]
はい! よろしくお願いします 😸分からない点があれば気軽に mention してください ;)
