### ISSUE TITLE
Docs 配下のページ閲覧後にDocsのindexページをダイレクトに表示させると Routing Error になる。

### ISSUE THREAD

**Issue by yu-san-19** [coderdojo-japan/coderdojo.jp#290]
## 流れ
coderdojo.jp/docs 配下のドキュメントならなんでもいいのですが、仮に憲章（charter）にアクセスしていたとすると、
https://coderdojo.jp/docs/charter を閲覧
⇒ そのままURLバーに直で https://coderdojo.jp/docs/ を表示
⇒ 別の（同じのでもいいですが）ドキュメントのリンクをクリック
⇒ Routing Error
といった感じになってしまいます 💦 

## 経緯

丁度、こちらのdocsページのコードを参考にして開発をしようと、とりあえずローカルの環境にコピーをして実行したところ、上記のエラーが発生したので、試しに coderdojo.jp の方も同じ事やってみると同様に発生した、という感じです。

https://twitter.com/yu_san_19/status/975363407741206530

なかなかダイレクトにURLバーでページ遷移する方もおられるとは思いませんが、（危険ですし。）こういうことがありました、というのだけご報告させていただきます。

**Comment by yasulab** [comment]
あー、Trailing Slash のバグですね 💦 https://coderdojo.jp/docs/ ( ⚠️ 最後にスラッシュをつけるのが重要) にアクセスすると、次のような URL に変化することが確認できました 🐛 👀 

https://coderdojo.jp/docs/docs/charter

**Comment by yasulab** [comment]
バグ報告ありがとうございます! 😸
