### ISSUE TITLE
モバイル版ニュースレターの「購読」ボタンの手前に余白を追加したい

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/coderdojo.jp#293]
[![ニュースレター購読](https://idobata.s3.amazonaws.com/uploads/attachment/image/975832/32c7827a-c5d4-4677-938f-be1188b77def/34D5CFC3-3B4C-4AFF-8DDE-4E46BD4D7F56.jpeg)](https://coderdojo.jp/#news)

モバイル版のemail入力フォームと購読ボタンとの間に、余白スペースを入れたい。余白スペースの量は、入力フォームとその手前の文章と同じくらいをイメージしています🤔💭

cf. https://coderdojo.jp/#news

**Comment by AnaTofuZ** [comment]
なるほどモバイル版…HTMLでスマートフォンから来た場合の判定をさせるなどになるんですかね 🤔 ちょっと調べてみます

**Comment by AnaTofuZ** [comment]
調べると dojosの表示に関しては `dojos.html+smartphone.haml` などと smartphone用のhamlがあった
これは `rack-user_agent` のgemで操作できるらしい

**Comment by yasulab** [comment]
ありがとうございます! よろしくお願いします 😸
