### ISSUE TITLE
Highcharts Error 16: Already defined in the page

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/coderdojo.jp#299]
[Stats ページ](https://coderdojo.jp/stats)を開くと、ブラウザの Console 上でこんなエラーが出力されていることを確認しました 🐛🔍 

```
application-41e1ed3ee1170ddeb711b3b476d271c917797cec688a1ccbd3a689be6f4386da.js:35 Uncaught Error: Highcharts error #16: www.highcharts.com/errors/16
    at w (application-41e1ed3ee1170ddeb711b3b476d271c917797cec688a1ccbd3a689be6f4386da.js:35)
    at application-41e1ed3ee1170ddeb711b3b476d271c917797cec688a1ccbd3a689be6f4386da.js:35
    at application-41e1ed3ee1170ddeb711b3b476d271c917797cec688a1ccbd3a689be6f4386da.js:35
    at application-41e1ed3ee1170ddeb711b3b476d271c917797cec688a1ccbd3a689be6f4386da.js:35
```

エラーメッセージにリンク先 (https://www.highcharts.com/errors/16) が添付されていて、辿ってみると原因はこれっぽいです🤔💭

> ### Highcharts already defined in the page
> 
> This error happens the second time Highcharts or Highstock is loaded in the same page, so the Highcharts namespace is already defined. Keep in mind that the Highcharts.Chart constructor and all features of Highcharts are included in Highstock, so if you are running Chart and StockChart in combination, you only need to load the highstock.js file.

cf. https://www.highcharts.com/errors/16

**Comment by nalabjp** [comment]
highchartsとhighstockをどちらもrequireすると出るみたいですね。
READMEのとおりに設定していたんですが😅

**Comment by yasulab** [comment]
> highchartsとhighstockをどちらもrequireすると出るみたいですね。
> READMEのとおりに設定していたんですが😅

なるほど! もしかしたら README を修正してあげると良いかもしれないですね ;)

**Comment by nalabjp** [comment]
https://github.com/michelson/lazy_high_charts/pull/239
PRとissueも既にあるみたいですが、マージされてないみたいですねー😢

**Comment by yasulab** [comment]
なるほど、現在対応中みたいですね ;) 共有ありがとうございます! 😆
