### ISSUE TITLE
CoderDojo 西成を非表示にしたい

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/coderdojo.jp#314]
1). coderdojo.jp のトップページからは非表示としつつも、開催したという事実が消えるわけではないので、 2). [統計データ](https://coderdojo.jp/stats)としては残しておきたい。一方、 3). 統計情報の最新の Dojo 数では、カウントしないようにしたい。

1.〜3. のやりたいことを満たそうとすると、結構修正するところは多そう...? 🤔💭

関連 Issue: https://github.com/coderdojo-japan/coderdojo.jp/issues/310

## 参考: CoderDojo 西成について

> CoderDojo Nishinari Osakaにご参加いただいたみなさま
> 
> お世話になります。CoderDojo Nishinari Osaka　浦方と申します。
> 
> いつもご参加くださり、また応援をいただき、ありがとうございます。
> 
> CoderDojo Nishinari Osakaについてご報告をいたします。2016年８月よりスタートして、これまで月１回のペースで開催してきましたが、３月より活動を一旦休止することなりました。そして、名称を改め今後は「山王プログラミング教室」として、2018年５月より月１回ペースでの開催を予定しております。
> 
> CoderDojoとしての活動ではなく「山王プログラミング教室」としての活動となります。実施内容については、これまで通りです。
> 
> 次回の開催日程については、改めてお知らせをいたします。よろしくおねがいします。

cf. https://www.facebook.com/coderdojo.nishinari.osaka/posts/588833824812579

**Comment by yasulab** [comment]
> CoderDojo Nishinari Osakaにご参加いただいたみなさま
> お世話になります。浦方です。
> CoderDojo Nishinari Osakaを改め「山王プログラミング教室」として再スタートすることになりました。

cf. https://www.facebook.com/coderdojo.nishinari.osaka/photos/a.283716175324347.1073741828.281889288840369/607396646289630/

**Comment by yasulab** [comment]
🤔.oO(データを削除する方法、まだそんなに確立していなかった印象がある。今回を機にフローを確立させたい)

**Comment by yasulab** [comment]
@naopontan 以前アナグラさんにお願いした次の Issue/PR の進め方を参考にして進めてみていただければ! 😸 

### アナグラさんに最初にお願いした Issue と、そのPR
- Issue: https://github.com/coderdojo-japan/coderdojo.jp/issues/259
- PR: https://github.com/coderdojo-japan/coderdojo.jp/pull/261

**Comment by naopontan** [comment]
おっ、雰囲気わかって参考になりますー 😸 
只今、情報収集と環境構築中... 💦

**Comment by naopontan** [comment]
# チェックリスト

私なりにチェックリスト考えてみました。

- [x] Ruby/Rails の環境構築
  - postgresql
- [x] rake テストの実行 & rails server で動作確認
- [ ] 構造の理解
- [ ] 要件の理解
  - トップページは非表示
  - 統計データとしては残す
  - 統計データの最新のDojo数はカウントしない
- [ ] 問題解決の方法を提案
- [ ] 実装

## 進捗報告

今はモデル構造が大体わかったところです。
まだ解析途中ですが、、、

- EventHistory と DojoEventService がまだモヤッとしてる
- db/dojos.yml  → Dojoモデルの関係は一方通行なのかな？
- 「統計データ」とは？
- DojoEventService モデルと db/dojo_event_service.yml の関係もモヤッと中
- spec 読んだり... (RSpec 勉強中 💦 )

(明日中には構造を理解して、実装を考えることができたらいいなー)

**Comment by naopontan** [comment]
仕様について教えてください。

> 1). coderdojo.jp のトップページからは非表示としつつも、開催したという事実が消えるわけではないので、 2). 統計データとしては残しておきたい。一方、 3). 統計情報の最新の Dojo 数では、カウントしないようにしきたい。

2) と3) については統計情報画面での数値はどう変化しますか？(以下の理解であってますか？)

- 「83 / 140 dojos」の部分は変化しない (残しておきたいのでそのまま)
- 「最新データ」のところの [道場数/開催回数/参加者数] は西成(非表示対象)を集計対象としない
- 「全国の道場」のところは近畿地方の 31 が 30になる（西成は近畿地区だから）

以下に統計情報の画面キャプチャを貼り付けます。
↓
![fireshot capture 9 - - coderdojo japan - https___coderdojo jp_stats](https://user-images.githubusercontent.com/399910/40224164-4d3fe1dc-5ac0-11e8-8395-9b8c2273925d.png)

**Comment by yasulab** [comment]
質問ありがとうございます! 😸 それぞれにお答えしますね ;)

> 「83 / 140 dojos」の部分は変化しない (残しておきたいのでそのまま)

統計情報の最新の Dojo 数ではカウントしないようにしたいので、削除後の統計情報としては `82 / 139` かなぁと考えています。

> 「最新データ」のところの [道場数/開催回数/参加者数] は西成(非表示対象)を集計対象としない

僕の書き方がよくなかったですね >< 💦 削除後は道場数を `-1` にしつつも、開催したという事実が消えるわけではないので、開催回数と参加者数はDBにある統計データをそのまま使えば良いかなと考えています🤔

一方、誤って別名称のイベントが統計対象とならないよう、統計スクリプトの対象からは外しておくと良さそうですね ;)

> 「全国の道場」のところは近畿地方の 31 が 30になる（西成は近畿地区だから）

はい! ここの部分は認識の通りです 😸  ✅ ✨ 

他にも何か気になる点があればお気軽にご連絡ください! 👍 ✨

**Comment by nalabjp** [comment]
👀

**Comment by naopontan** [comment]
@nalabjp よろしくお願いします!  👂

**Comment by yasulab** [comment]
> (できればその Dojo の存続期間は過去の道場数に反映させたいけど、これは結構難しそうかも...? 😓 )

ジャストアイデアですが、  Dojo has_many Suspensions みたいなモデルにして、Suspension の期間中は  (期限の指定がない場合は実質ずっと) 非表示にするという案が、ふと浮かびました 🤔💭ジャストアイデアですが、とりあえず共有しますね >< 💦

**Comment by naopontan** [comment]
私がお話を聞いて真っ先に思いついたのは 論理削除でした。
昔、論理削除の gem を使ってすんなりと使えた記憶があったので。

ただ、 @nalabjp さんの
https://github.com/coderdojo-japan/coderdojo.jp/issues/310#issuecomment-376120728
を見ると「ふむふむ。なるほど、私の考えは安易なのかも」と思いました。 📝 

論理削除以外で Dojo モデルに state的なのを持たせないとなると @yasulab さんアイデアに近いものになるのかなーと。（恐縮ですが私も同じ考えがモヤッと浮かんではいました）
色々と考えましたが、 *論理削除 / Suspentinos で状態管理* 以外のアイデアが思いつかないです... 😟 

あと、コードリーディングについては lib 配下の statistics まわりがまだ完全には把握しきれていない状況です 💦

**Comment by naopontan** [comment]
@yasulab 表示/非表示の制御をする権限はどうなりますか？
想像するに PR をもらって、管理者がそれを許可/拒否するイメージでしょうか？

画面のI/Fをもっていないようなので yaml ファイルでやり取りしている認識です
- Dojo モデルと dojos.yaml
- DojoEventService モデルと dojo_event_services.yaml

suspentions.yaml が追加されるイメージ!? 🤔

**Comment by yasulab** [comment]
現在は yaml の I/F がありますが、それ以外でもベターな方法があればそちらを採用したいとは考えています 😸 どうやると良さそうですかね? 🤔💭

**Comment by yasulab** [comment]
> 稀に道場のチャンピオンが PR を送ってくる。って感じなんですかね？ 🤔💭

@naopontan PR だったりメールだったりメッセージだったりですねぇ 📨 メールやメッセージの問い合わせが割合としては多いですが、コミュニティ拡大に伴って対応コストも増加してしまうので、(可能なら) 少しずつ PR に寄せていきたいなと考えています。PR なら内容を確認してマージボタンを押すだけなので ✅💨 

メンターが送った PR かチャンピオンが送った PR なのかは今のところ気にしてはいないですね ;)

> Suspention モデルの方向で設計を進めていいでしょうか？

現状では Suspension モデル以外にも、僕が https://github.com/coderdojo-japan/coderdojo.jp/issues/310#issuecomment-376125789 でコメントした次の設計も良さそうかなと考えていますが、いかがでしょうか?

> 例えば CoderDojo Zen API とのスムーズなデータ連携ができるようになったら、 Zen 上で非アクティブに変更したら coderdojo.jp からも非表示になる みたいな実装にも繋がって色々と便利にしていける可能性が広がりそうです 💭

**Comment by naopontan** [comment]
> わせが割合としては多いですが、コミュニティ拡大に伴って対応コストも増加してしまうので、(可能なら) 少しずつ PR に寄せていきたいなと考えています。PR なら内容を確認してマージボタンを押すだけなので ✅💨

如何に *「PR に寄せていくか？」* の課題を考えて、*「最終判定はPR対応で」* の方が理想っぽいですね 😸 

> 現状では Suspension モデル以外にも、僕が #310 (comment) でコメントした次の実装方針も良さそうかなと考えていますが、いかがでしょうか?

CoderDojo Zen はアクティブ/非アクティブのステータスを持っているのですね。
良さそうですが、 CoderDojo Zen をよく分かっていなく、その場合はもっと工数がかかりそう＆私のスキルでは少々不安です 😓 

他にも CoderDojo Zen と連携したい機能がたくさんあるなら Issue 立ててもいいと思います

**Comment by yasulab** [comment]
> 「最終判定はPR対応で」 の方が理想っぽいですね 😸

いえ、PR 対応より CoderDojo Zen 対応の方が理想的かなと考えています。Zen はすべての Dojo が必ず持っているアカウントで、かつ、主に Foundation 側で活動が Dojo のステータスを定期的にチェックしているので、

- Zen で非アクティブになると coderdojo.jp でも非表示になる
- Zen で　アクティブになると coderdojo.jp でも　表示される

といった方が、Dojo 運営者からすれば Zen アカウントの状態だけを管理すれば良いため、 **Zen のステータスを管理して、かつ、yaml を変更する** という運営者側の手間が減りかなと思いました🤔💭僕としても Zen の状況を見てソフトウェアが自動で管理してくれるのであれば、PR の確認＆マージすら不要になるので嬉しいかなと感じています ;)

> CoderDojo Zen をよく分かっていなく、その場合はもっと工数がかかりそう＆私のスキルでは少々不安です 😓

これは個人のスキルの課題ですよね 😅 CoderDojo コミュニティ全体にとってよいカタチを目指していきましょう! 🔧💨 例えば「Aに掛かる工数があれば、Aを諦めて、BとCの2つを実装することができ、そちらの方が CoderDojo コミュニティにとってより良い方向につながる」といった提案であれば、もちろんその提案の方が良いと思います 👍✨ 

今回はリスクをとっていける安全な状況での開発なので (失敗したからといって契約不履行などが発生する状況ではないので)、 @naopontan さんのスキルを弊社の標準的なスキルセットに合わせていく意味でも、 @naopontan さんの現在のコンフォートゾーンに留まらない方が良いかなと思いました 😌 

どんどんチャレンジしてきましょう! 💪 ✨

**Comment by yasulab** [comment]
> CoderDojo Zenまわりの調査をして、もう少しボリューム感を把握してから方向性を決めましょうかね？

はい! 良いと思います 👍✨ アウトプットの形は必ずしもコードだけではないと思うので、 **その試行錯誤の過程さえ可視化されていれば** 、メンテナンスや引き継ぎなどの観点から見てもむしろコード量が少ない方が良い場合は多いかなと考えています ;)

cf. [より正しいアプローチ、３行のコード - Qiita:Team](https://yasslab.qiita.com/yasulab/items/986f9c66dc34a3c9f781#comment-3747a9a06239b6993d36)

**Comment by yasulab** [comment]
> その試行錯誤の過程さえ可視化されていれば

具体的には、例えば今回のような見積もりを行う際も、「何をどのように調べていくか」を書き出しながら進めていていくと、周りの人たちもサポートしやすいかなと思います 👀✨ 

cf. [直近のイベント情報を集計するtaskの追加 #297](https://github.com/coderdojo-japan/coderdojo.jp/pull/297)

**Comment by naopontan** [comment]
了解しました。コードに限らずアウトプットも出していきます 💪

**Comment by naopontan** [comment]
# zen.coderdojo.com とその API の調査

1. zen.coderdojo.com って何だ？ → 本家っぽい
1. zen.coderdojo.com にアクセス API に関するリンクが無いか一通り見てみる
1. 見当たらないので `zen coderdojo api` でググってみる。 https://zen.coderdojo.com/documentation#/api を発見
1. アカウントがあると情報量が増えそうなのでアカウント作ってみる ← 今ここ

簡単なサンプルと sandbox 的な場所があれば実際に動かしてみたほうが理解早そうだけど、あるかなー？ って感じで調査中

**Comment by naopontan** [comment]
私が Issue 立ててもいいのかな？立てちゃいますね 📝

**Comment by naopontan** [comment]
> CoderDojo Nishinari Osakaについてご報告をいたします。2016年８月よりスタートして、これまで月１回のペースで開催してきましたが、３月より活動を一旦休止することなりました。そして、名称を改め今後は「山王プログラミング教室」として、2018年５月より月１回ペースでの開催を予定しております。

**一旦休止** とありますが、このケースはどちらかというと **廃止** 扱いですよね?
#310 のケースは再開の見込みがあるので休止でいいと思います。

休止と廃止は違いますね。確か zen 上でも `deleted` がありました。

西成に関しては zen 上ではどういう扱いになるんだろ... 🤔

**Comment by naopontan** [comment]
@yasulab 
お願いがあります。 @yasulab が持っている zen の道場でテスト用のを教えてもらえますか？
そして、その道場に「チャンピオンとして参加」していいですか？
道場の編集画面が見れるか試したいです。
（道場の登録者とチャンピオンは権限が別物かもしれませんが...）

**Comment by yasulab** [comment]
招待や参加ができるのは verified された Dojo のみなので、Pending 中の Dojo には仕様上招待したり参加することはできないですね >< 💦 

Verified されている CoderDojo Okinawa はもともと僕が立ち上げた Dojo を引き継いでいる関係で、僕もチャンピオン権限を持っていますが、現チャンピオンは比嘉さんなので、もし Okinawa の権限を使う場合は比嘉さんに一度問い合わせておくと良さそうです🤔💭

**Comment by naopontan** [comment]
ありがとうございます。
比嘉さんに問い合わせてみますね。あと、やっぱりテスト用の道場があったほうがやりやすいので CoderDojo Global Slack 等で「テスト用の道場を作ってもよいか？」を質問してみますね。
今後も考えると、あったほうがやりやすいので。

**Comment by yasulab** [comment]
ですね! よろしくお願いします 😸

**Comment by naopontan** [comment]
宜野湾の山口さんにお願いして「チャンピオンとして参加」させてもらいました。
https://zen.coderdojo.com/dojos/jp/ri4-ben3-chong1-sheng2-xian4-yi2-ye3-wan1-shi4/ginowan-okinawa-okigin-s-p-o

そうすると無事、道場の編集権限がもらえて画面が見えるようになりました 🎉 

![fireshot capture 12 - edit dojo i coderdojo zen_ - https___zen coderdojo com_dashboar](https://user-images.githubusercontent.com/399910/40466941-d6890bde-5f62-11e8-9614-7184e0cfc064.png)

（本番データで、しかも本当の管理者ではないので勝手にいじることはしませんが、やっぱりあると助かる。Thanks 山口さん)

**Comment by yasulab** [comment]
おぉ! すごい! 🎉✨ 

今回の開発はオープンに行なっているので、こちらの Issue で開発・議論を進めていることを山口さんにお伝えしても良いかもしれないですね 😸

**Comment by naopontan** [comment]
山口さんには伝え済みです。感謝です  😄  このURLも教えてますー 🔗 
後から追加されたチャンピオンでも同権限が付与されるっぽい事がわかったのは収穫でした。

**Comment by yasulab** [comment]
さすがです!! 👍🆒✨

**Comment by yasulab** [comment]
Fixed by https://github.com/coderdojo-japan/coderdojo.jp/commit/b8a6027d8d1da801bdc49afbdcf664ee3a217245
