### ISSUE TITLE
CoderDojo 呉を coderdojo.jp 掲載する

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/coderdojo.jp#316]
[CoderDojo 呉](https://www.facebook.com/CoderDojo%E5%91%89-206840799906741/?modal=admin_todo_tour)から coderdojo.jp への掲載依頼が来たので、これに対応したい。(申請内容は別途共有)

対応例1: https://github.com/coderdojo-japan/coderdojo.jp/commit/cf2d579ec961f2690f2a32220e0f8b17113412f0
対応例2: https://github.com/coderdojo-japan/coderdojo.jp/issues/259

cf. [作業メモの例 - OSS Gate](https://www.youtube.com/watch?v=kwQ9ZzslxxA&index=7&list=PLg41HKRyxE6gIvt3sM09REYvLYkRRkuaS)

## チェックリスト

- [x] [新規Dojoの追加方法](https://github.com/coderdojo-japan/coderdojo.jp/blob/master/docs/how-to-add-dojo.md)を読んでみた?
- [x] Ruby/Rails の環境構築はできた?
   - Hint: トップページの表示には環境変数は不要 (なはず)
- [x] db/dojos.yaml に Dojo 情報を追記した?
   - Hint: `be rails dojos:update_db_by_yaml`
   - 掲載する情報は @yasulab まで問い合わせてもらえれば ;) 📨 
- [x] DBからIDを取得して db/dojos.yaml に追記した?
   - Hint: `be rails dojos:migrate_adding_id_to_yaml`
- [x] ローカル環境で Dojo が表示できた?
- [x] 統計情報にイベント管理サービスを登録できた?
- [x] 本番環境に反映された?
- [ ] 上記のドキュメントに加筆修正した方が良い箇所はある?

## 作業の完了条件

- [x] CoderDojo 呉が coderdojo.jp に掲載されている
- [x] 依頼されたロゴが表示されている
- [x] 掲載しているロゴは TinyPNG などで画像圧縮されている
- [x] リンク先が適切である
- [x] 集計対象にも登録されている (毎週月曜日に統計情報が更新される)

**Comment by aokabin** [comment]
cf. [作業メモの例 - OSS Gate](https://www.youtube.com/watch?v=kwQ9ZzslxxA&index=7&list=PLg41HKRyxE6gIvt3sM09REYvLYkRRkuaS)
を参考に見てみた、なるほど、GitHubのIssueにどんどんコメントとして残していく、それは良さそう！
ということでメモをガンガン残していくスタイルにする

上のチェックリストから進めていこうかな、ということで新規Dojoの追加方法を読んでみる

**Comment by yasulab** [comment]
良いと思います! 👍 ✨

**Comment by yasulab** [comment]
.oO(他のところでも結構評判が良いみたいなので、この動画頑張って収録・編集した甲斐がありました 💪 📹 ✨ )

> 収録・編集: YassLab
> https://yasslab.jp/

**Comment by aokabin** [comment]
db/dojos.yamlに書くだけで反映される...？のかな？

内容はさっくり2つのことが書いてあり、
1. Dojo DBの追加手順
1. 集計対象の追加

両方ともyamlファイルを書くだけで良さそうではあるかなぁ
一応`1.`に関しては、
> yaml ファイルに各項目を追記したら、$ bundle exec rails dojos:update_db_by_yaml を実行してDBに新規Dojo情報を反映します。その後 $ bundle exec rails dojos:migrate_adding_id_to_yaml を実行します。
> 
> yamlファイルにidおよびorderが動的に更新されたことを確認できたら Add CoderDojo [Dojo名] でコミットをします。
という記述があるので、多少コマンドを入力する必要はありそうではあるが、あくまでも**orderの値を自動紐付けする場合**である(と読み取った)ので、手入力するなら必要はないかも...？

#### 個人メモ
1. db/xxx.yamlへの記述が、Rails標準の機能なのかgem使ってるのか調べてみる
2. dojosコマンドが追加されてる、追加の仕方を知りたい

**Comment by yasulab** [comment]
当時より便利タスクが増えたりドキュメントが用意されたりで少しコンテキストが異なりますが、全く同じタスクをアナグラさんにお願いした時の例が https://github.com/coderdojo-japan/coderdojo.jp/issues/259 になるので、こちらも参考になりそうです :)

**Comment by aokabin** [comment]
情報をIDやorderの情報以外を書いたところで
1. `bundle exec rails dojos:update_db_by_yaml `
2. `bundle exec rails dojos:migrate_adding_id_to_yaml `
を実行
見た目には何か違いが出たわけではなかったので、成功したのか失敗したのかわからなかった。。。
2はyamlファイルがアップデートされたので、わかったけど
ログが出るわけではないので、何がどう変更されているのか、変更されていないのかがわからなかった。

ID2番という若い番号が割り振られたのも、何かミスがあったんじゃないかと不安...
(auto incrementとかを想像しがちなので、100個以上Dojoがあるのに2番は若すぎる)

心配していても埒があかないので、この時点で`rails s`して確認してみる

![2018-04-11 15 43 15](https://user-images.githubusercontent.com/3102940/38600467-2bda4070-3d9f-11e8-97d7-64c0d5eeacde.png)

おー、追加されてるされて...る...？
ふ、二つ追加されている...

`rails c` でコンソールから確認
```ruby
[1] pry(main)> Dojo.where(name: "呉 (広島)")
  Dojo Load (0.9ms)  SELECT "dojos".* FROM "dojos" WHERE "dojos"."name" = $1  [["name", "呉 (広島)"]]
=> [#<Dojo:0x00007fee7d996948
  id: 2,
  name: "呉 (広島)",
  email: "",
  order: "342025",
  description: "呉市で毎月１回開催",
  logo: "/img/dojos/kure.jpg",
  url: "https://www.facebook.com/CoderDojo%E5%91%89-206840799906741/",
  tags: ["Webサイト"],
  created_at: Wed, 11 Apr 2018 15:31:50 JST +09:00,
  updated_at: Wed, 11 Apr 2018 15:31:50 JST +09:00,
  prefecture_id: 34>,
 #<Dojo:0x00007fee7d9967b8
  id: 1,
  name: "呉 (広島)",
  email: "",
  order: "342025",
  description: "呉市で毎月１回開催",
  logo: "/img/dojos/kure.jpg",
  url: "https://www.facebook.com/CoderDojo%E5%91%89-206840799906741/",
  tags: ["Webサイト"],
  created_at: Tue, 10 Apr 2018 18:26:35 JST +09:00,
  updated_at: Tue, 10 Apr 2018 18:26:35 JST +09:00,
  prefecture_id: 34>]
```

なんか怪しいなぁ
DB情報がなんか怪しいので、リセットしてみる

`rails db:migrate:reset; rails db:seed; bin/setup`

この時点で居る...！？
```ruby
[2] pry(main)> Dojo.where(name: "呉 (広島)")
  Dojo Load (1.1ms)  SELECT "dojos".* FROM "dojos" WHERE "dojos"."name" = $1  [["name", "呉 (広島)"]]
=> [#<Dojo:0x00007fe0f9a57968
  id: 1,
  name: "呉 (広島)",
  email: "",
  order: "342025",
  description: "呉市で毎月１回開催",
  logo: "/img/dojos/kure.jpg",
  url: "https://www.facebook.com/CoderDojo%E5%91%89-206840799906741/",
  tags: ["Webサイト"],
  created_at: Wed, 11 Apr 2018 16:00:37 JST +09:00,
  updated_at: Wed, 11 Apr 2018 16:00:37 JST +09:00,
  prefecture_id: 34>]
```

yamlファイルに書いてあるからsetupの時に入っちゃうのかな？
yamlファイルから呉を削除して再度setupしてみる

すると、ちゃんと居なかった！正解！

焦って先にyamlファイルを書いて、その後setupとかをすると、同じDojoが複数個DBに登録されてしまうっぽい
(IDが1になってたのは未だ気になるけど...)

![2018-04-11 16 40 52](https://user-images.githubusercontent.com/3102940/38602919-2c839406-3da7-11e8-825b-453cc011b8a7.png)

ちゃんとできてる！

次は統計情報！

**Comment by aokabin** [comment]
統計情報は、今回はFacebookを登録するだけだったのですぐ終わった。

**Comment by yasulab** [comment]
[１コメントあたりの量](https://github.com/coderdojo-japan/coderdojo.jp/issues/316#issuecomment-380358908)が結構デカい印象があるので、もっと細かい単位で作業ログを書き込んだ方が周りの人たち (今回の件でいえば僕やアナグラさん) がサポートしやすそうですね  ;)

僕の場合はいきなりドカッと情報量を書き込まれると、逆に読まない (正確には次にまとまった時間が取れるまで読まない) 事が多いです >< 💦 細かく作業ログを書いて行くと隙間時間に読めるので連携もしやすいかなと思います ;)

**Comment by yasulab** [comment]
OSS Gate の動画も細かくコメントしていたかと思いますが、具体的にはこのぐらいの量で作業ログを次々と書き込んでいってもらえると良いです 👍 
https://github.com/coderdojo-japan/coderdojo.jp/issues/259

**Comment by aokabin** [comment]
意識してみます！ありがとうございます！

**Comment by yasulab** [comment]
#321 で対応できたので、こちらの Issue 閉じますね ;) お疲れ様でした! ✨👏 

１点、Description の次の部分だけ ✔︎ を付けずに残してありますが、もし追記した方が良い箇所などあれば別途 Issue or PR で対応できればなと考えています 📝 💨 

> - [ ] 上記のドキュメントに加筆修正した方が良い箇所はある?
