### ISSUE TITLE
Scrivito の環境変数が無い場合は Scrivito に関するテストを実行しないように変えたい

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/coderdojo.jp#319]
## ストーリー

1. 現在の Test Suite には Scrivito に関するテストも含まれていて、それらのテストは Scrivito の環境変数がないと failed になる
2. Scrivito と関係ない機能をいじっているとき、その機能をいじった結果としてテストが落ちたのか、Scrivito の環境変数がないから落ちたのかの判別がつかない
3. Scrivito 周りの開発に携わっていない場合は、Scrivito 周りのテストは skip する形の方が良さそうでは? 🤔💭
   - Scrivito の Key/Tenant は必要な時に共有すればいい (kata ページと sotechsha ページ)
   - Rails の部分のみに触れればよい場合がほとんど。Scrivito が必要になる部分は Isolated になるべくしているので、上記ページに影響を与えることはない
   - 開発者の人は手元でテストを流した結果が見やすくなる

NOTE: デフォルトのテスト対象には含めないだけで、CI ではすべてのテストを実行する

## 課題
https://github.com/coderdojo-japan/coderdojo.jp/tree/3796f7121d9aab75297295fd8b8973cb3007fc6d の時点で Scrivito の環境変数がない場合に失敗するテストコード一覧。

```
Finished in 14.12 seconds (files took 5.62 seconds to load)
51 examples, 14 failures

Failed examples:

rspec ./spec/controllers/sotechsha_overview_page_controller_spec.rb:7 # SotechshaOverviewPageController GET #index set @sts_post
rspec ./spec/features/sotechsha_spec.rb:26 # Sotechsha GET /sotechsha/1 Datetime should be formatted
rspec ./spec/features/sotechsha_spec.rb:17 # Sotechsha GET /sotechsha SoTechSha link should be rendered
rspec ./spec/features/sotechsha_spec.rb:7 # Sotechsha GET /sotechsha/num Quizzes should be permalink
rspec ./spec/controllers/blog_post_page_controller_spec.rb:17 # BlogPostPageController GET Blog Post Page sotechsha post
rspec ./spec/controllers/blog_post_page_controller_spec.rb:7 # BlogPostPageController GET Blog Post Page normal blog post
rspec ./spec/features/news_spec.rb:6 # News GET /news/2016/12/12/new-backend Title should be formatted
rspec ./spec/requests/sotechshas_spec.rb:15 # Sotechshas GET /sotechsha/gazou Gazoulink should be permalink
rspec ./spec/requests/sotechshas_spec.rb:6 # Sotechshas Quizzes should be permalink Quizzes should be permalink
rspec ./spec/controllers/sessions_controller_spec.rb:10 # SessionsController GET #create param unmatch
rspec ./spec/requests/news_pages_spec.rb:5 # NewsPages GET /news/2016/12/12/new-backend Blog post should be rendered
rspec ./spec/features/users_spec.rb:33 # Users log in with valid information
rspec ./spec/features/users_spec.rb:23 # Users log in with invalid information
rspec ./spec/features/users_spec.rb:24 # Users log in with invalid information
```

**Comment by AnaTofuZ** [comment]
Rspecにはskipというものがあるようなので、これを使えば実現できるのかなと思いました。
調査してみます

**Comment by yasulab** [comment]
あざす! 😸 環境変数があるかないかで分岐させることができれば良いのかなぁ🤔

とはいえ CI の方では Scrivito に関するテストコードも含めたすべてのテストを実行したいなと考えています ;)

**Comment by yasulab** [comment]
ストーリーを追記しました!

@AnaTofuZ お...? そう言えば @nalabjp さんに同様の課題をすでに解いてもらっていたことを思い出しました🤔💭

`.travis.yml` の次のあたりのコード周りをうまいやり方がわかりそうです ;)

>   - bundle exec rake db:migrate --trace
>   - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bundle exec rspec spec; fi
>   - if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ "$TRAVIS_PULL_REQUEST_SLUG" = "coderdojo-japan/coderdojo.jp" ]; then bundle exec rspec spec; fi
>   - if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ "$TRAVIS_PULL_REQUEST_SLUG" != "coderdojo-japan/coderdoj
> o.jp" ]; then bundle exec rspec spec --tag ~@scrivito; fi

**Comment by yasulab** [comment]
上の実装が行われたコンテキストはこちらですね ;)
だいたい同じコンテキストなので、ちょっと wrap する or ドキュメントで書くぐらいで大丈夫かも?
https://github.com/coderdojo-japan/coderdojo.jp/issues/160

**Comment by nalabjp** [comment]
spec/rails_helper.rbあたりで環境変数をチェックして、
無かったらrspecのmetadata（tag）にフラグを立てるってやればヨサソウですね。
そうすると、 https://github.com/coderdojo-japan/coderdojo.jp/issues/319#issuecomment-380037822 の.travis.ymlにべた書きしてある条件も書き換えられるかと思います。

**Comment by shishi** [comment]
scrivito に関するテスト、とは metadata に `scrivito: true` があるテストという理解でよいでしょうか？それらが必ずしも環境変数を含んでいるわけではなさそうですが趣旨でいうとscrivitoに関するものならskipしたいのかなと

**Comment by yasulab** [comment]
> 趣旨でいうとscrivitoに関するものならskipしたいのかなと

ですね! 先日 @shishi さんが遭遇したように、Scrivito を触る必要のない開発においては、少なくとも手元でテストを実行したときはデフォルトでは Scrivito に関するテストを skip させても良いかなという趣旨になります🤔💭

一方で Scrivito 自体は本番環境で使われているので、CI 上では Scrivito を含むすべてのテストを実行したいと考えています! 🔧 🤖  ✅

**Comment by shishi** [comment]
なるほど。では `scrivito: true` と環境変数を持っているかで判断しようと思います。

**Comment by yasulab** [comment]
よろしくお願いします! 😸 ✨
