### ISSUE TITLE
Memory Quota Exceeded になった原因を調査する

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/coderdojo.jp#320]
とりあえずは Hobby -> Professional Dyno に変更することが対処した。次の３つが終わったら、ひとまずこの Issue は閉じようと思います🤔💭

- [ ] 原因を調査する
- [ ] 原因および対策案を Issue に書き出す
- [x] (可能そうなら) Hobby Dyno に戻す

**Comment by yasulab** [comment]
> - [x] (可能そうなら) Hobby Dyno に戻す

`$ heroku restart` するだけで大丈夫そうだったので、これだけ先に対応しておきました ✅

**Comment by AnaTofuZ** [comment]
情報としてアラートが発生したのが3日前となっていたのでherokuのMetricsからの原因調査は難しいようでした

**Comment by yasulab** [comment]
あらー、なるほど >< 💦 調査 thx! 

Heroku 上で追跡できない以上、もう一回同様のアラートが出るまでは一旦この Issue は Close しちゃいますね ;)

もし再現性のあるアラートなら近々また発生すると思いますし、その時に同様の Issue をまた立ち上げますね 📝 💨

**Comment by yasulab** [comment]
一応断念した理由も Description に反映しておきました ;)
