### ISSUE TITLE
Docker環境の整備

### ISSUE THREAD

**Issue by shishi** [coderdojo-japan/coderdojo.jp#346]
現在のcoderdojoプロジェクトではDockerなどの仮想環境を利用した開発環境を整えられる状態にはなっていないのでこれを用意してよりプログラミングにスムーズに入れるようにしたい。

必要そうなこと

* rails用イメージ
  * rubyのバージョンはGemfileに記載のものに合わせる
  * rails_helperによればcapybaraは使用していないようなのでchrome-headless等はとりあえずなし
  * jquery使用中でwebpackerは必要ない？
* PostgreSQL用イメージ
  * 特にカスタマイズはいらなさそう
  * バージョンは最新で良いかな？
* data volume
* docker-compose
* READMEへの記載

**Comment by yasulab** [comment]
Issue 立てありがとうございます! 😸 coderdojo.jp にコントリビュートするためのハードルが下がるのはいいですね! ぜひお願いします 🙏 ✨
