### ISSUE TITLE
テストに不必要な環境変数を削除する

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/coderdojo.jp#348]
cf. Docker環境整備 #347

>  Scrivitoが必要とする環境変数のうち、"SCRIVITO_EMAIL"と"SCRIVITO_PASSWORD"は特定のものと定まっていないということなので環境変数にする必要はなく、テストにふさわしい文字列をテスト中で設定しておけば良いのではと思いました。

**Comment by shishi** [comment]
@yasulab 

このメソッドの意図が気になります。もしこの環境変数を削除してしまうならこのメソッドも削除する方向になると思いますが何か問題ありますか？

**Comment by yasulab** [comment]
あー、これは確か User モデルの代用として臨時で作ったログイン機構な気がします🤔💭  https://coderdojo.jp/sotechsha や https://coderdojo.jp/kata を Scrivito を使って編集する際にログイン・ログアウトできるようにしたかったので。

なのでこれを削除すると上記のページが編集できなくなっちゃうかもですね >< 💦  そうするとソーテック社のページを著者さんや編集者さんが編集できなくなったり、僕が Kata ページを編集できなくなりそうです 🙀

**Comment by yasulab** [comment]
(思い出すのに時間がかかってしまって申し訳ないです...!! 🙇 💦 )

**Comment by nalabjp** [comment]
秘匿情報を環境変数に入れておくのは割とよくある使い方だと思うのですが、
このissueが抱えている具体的な問題はどういうケースなのでしょうか？
「テストに不必要な環境変数を削除する」というタイトルなのに、
プロダクションコードを消すことになりそうという方向に向かっているのが気になっています。

**Comment by yasulab** [comment]
落ち着くところとしては臨時的に作った環境変数+セッションによるログイン機構ではなく、User モデルをちゃんと実装して環境変数を削除するとかですかね🤔💭 

一方、運用的な実用性の面から考えると、[README で使ってアカウントを手動で発行 (共有) するよ〜](https://github.com/coderdojo-japan/coderdojo.jp#2-coderdojo-kata-%E3%81%AE%E5%9F%B7%E7%AD%86%E7%B7%A8%E9%9B%86) と謳っているものの、Scrivito を使って Kata を編集したい人が一向に現れないのが現状ですね 😭 

話が徐々に別の方向にずれそうですが、根本的には Scrivito ではなく Markdown + GitHub + PR で Kata を運用した方がいいのかもしれないなぁというアイデアはあります (とはいえそもそも編集したい人がいないというケースもありうるので、Markdown + GitHub + PR にしても何も変わらないという可能性もありそうです) 💦

**Comment by shishi** [comment]
@nalabjp 

> 秘匿情報を環境変数に入れておくのは割とよくある使い方だと思うのですが

そう思っていなかったのが調べてみたらそういう使い方になっていたというところですね。

@yasulab 

つまり運用上は唯一の"SCRIVITO_EMAIL"と"SCRIVITO_PASSWORD"の組み合わせがあり、ログイン判定的なものを簡易にとりあえず実装されたものということですね。それで済む範囲のことなら用もなくちゃんとしたものを作る必要はないかなと思います。

> Markdown + GitHub + PR で Kata を運用した方がいい

Scrivitoが複雑さを生み出している(そしてテストを遅くしている)のは間違いないのでそのようになるのは僕も賛成です。

> README で使ってアカウントを手動で発行 (共有) するよ〜 

もしかしてこの辺お願いするのが手間で言いだしにくいという人もいたりするかもですね。

**Comment by yasulab** [comment]
> もしかしてこの辺お願いするのが手間で言いだしにくいという人もいたりするかもですね。

うーん、どうですかね🤔 例えば https://coderdojo.jp/docs は既に Markdown + GitHub + PR で対応できる形式になってますが PR が来た覚えがないので >< 💦 

PR になれていないのかというとそうでもなくて、例えば nalabjp さんと一緒に実装した yaml 形式での Dojo 情報を管理する仕組み (`/db/dojos.yaml`など) はよく使われているので、単純にあまり編集したい人がいないのかなという印象ですね。

その点から論じると、PR や Git/GitHub の仕組みを知らなくても Wiki のように簡単に編集できる Scrivito の方が現状では適切そうですね 👀  (少なくとも著者や編集者の方々からは好評だったので 😊 ) 

cf. CoderDojo を支える Rails CMS の活用事例 - Speaker Deck
https://speakerdeck.com/yasulab/case-study-rails-cms-for-coderdojo

**Comment by yasulab** [comment]
> この間僕が整備したもので知らずにテスト実行してもこけることはなくなったので。

ですね! では一旦こちらの Issue は閉じちゃいますね ;) また必要になった時に Re-open します!
