### ISSUE TITLE
footerで読み込んでいるWufoo formの整形

### ISSUE THREAD

**Issue by megane9988** [coderdojo-japan/coderdojo.jp#353]
Wufooの仕様として、

- iframeでformが読み込まれる
- デザインを設定する場合には、外部のcssのファイルを置き、それを読み込む形となる

ということで、フォームの整形するためのcssを設置しようとおもいます。
設置する場所は本来であればcssがAsset Pipelineによって書き出させる場所に配置するべきですが、
そうすると、 `application-704027e05647d21792a724742db75152c69ea82258c636d830a1b996ecc87620.css`  というように、コンパイルされるたびにファイル名が変わってしまいます。

すると、Wufoo側でも都度、読み込んでいるcss名をを変更する必要があるため、現実的では無いと判断し、別途 `public/css/`  に `wufoo.css` を配置します。

**Comment by megane9988** [comment]
@yasulab 

本番反映された模様です。確認後、問題なければクローズ願います！

配置されたcss
https://coderdojo.jp/css/wufoo.css

結果の出力
https://coderdojo.jp/

cssによって操作した箇所

- フォームタイトルの非表示
- 必須のアイコンの非表示
- ボタンのデザイン（青地で白文字に）
- ボタンの配置を中央寄せに

wufooにおいて作成したテーマ
`coderdojojp_form`

**Comment by yasulab** [comment]
うまくいった事が確認できたので閉じます! ありがとうございました! 😸
