### ISSUE TITLE
DojoCastのRSSフィードを実装してiTunesから購読できるようにする

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/coderdojo.jp#363]
cf. DojoCast - Highlight people around CoderDojo communities by Podcast 📻✨
cf. https://coderdojo.jp/podcasts

cf. iTunes RSS generator - Apple (for Preview)
https://rss.itunes.apple.com/

[![image](https://user-images.githubusercontent.com/155807/50319636-b884c980-050b-11e9-9b0a-a227c0023500.png)](https://www.facebook.com/groups/coderdojo.jp/permalink/1964303593683030/?comment_id=1968089989971057)

**Comment by odlovesq** [comment]
podcast使ったことないのですが、面白そうなので着手しようと考えています。
作業は以下の流れを想定しています。

* rssフィードを作成
* ルーティングを設定
* podcastに登録

**Comment by yasulab** [comment]
どうぞどうぞ...!!! 🆒 d(￣ ￣)✨

**Comment by yasulab** [comment]
cf. https://coderdojo.jp/podcasts

**Comment by odlovesq** [comment]
ありがとうございます！

**Comment by odlovesq** [comment]
appleの公式ページに送信の手順が書いてました！
RSSフィードを作成したあと、テストや検証もする必要があるらしいです。

https://help.apple.com/itc/podcasts_connect/#/itc4f0f5ac7d

**Comment by odlovesq** [comment]
検証・送信・管理にpodcasts_connectにログインする必要があります。
その際Apple IDが必要になります。

https://podcastsconnect.apple.com/my-podcasts/new-feed

**Comment by yasulab** [comment]
おー、情報ありがとうございます! (＞人＜ )✨ あとでアカウント用意しておきますね ;)

**Comment by odlovesq** [comment]
ありがとうございます！助かります！！:star:

**Comment by yasulab** [comment]
Podcast アカウント作りました! 🍎 ✨ 

![image](https://user-images.githubusercontent.com/155807/53694735-6955f180-3df6-11e9-9b98-c0026776345f.png)

検証自体は個人アカウントでもできるようなので、アカウントは共有しなくても大丈夫かなと考えていますが (登録するときに僕のアカウントで行えばいいかなと考えていますが)、いかがでしょう?  🤔💭

**Comment by odlovesq** [comment]
ありがとうございます！！！

> 検証自体は個人アカウントでもできるようなので、アカウントは共有しなくても大丈夫かなと考えていますが (登録するときに僕のアカウントで行えばいいかなと考えていますが)、いかがでしょう? 🤔💭

了解です！！🎧
検証まで終わったら @yasulab さんに共有します。

**Comment by yasulab** [comment]
よろしくお願いします...!! (＞人＜ )✨
