### ISSUE TITLE
Heroku Review Apps を coderdojo.jp でも使いたい

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/coderdojo.jp#369]
yasslab.jp や railstutorial.jp では導入済み ✅ Review Apps はメッチャ便利で、 例えば[こういったテストで見抜きにくいエラー](https://github.com/yasslab/railsguides.jp/pull/765#issuecomment-450784473)に事前に気づけるし、デザインのレビューでもスクショなどをコメント欄に貼る必要がなくなるので、coderdojo.jp でも導入したい 🚀🚀🚀 ✨ 

Review Apps | Heroku Dev Center
https://devcenter.heroku.com/articles/github-integration-review-apps

**Comment by yasulab** [comment]
Heroku Review Apps 設定しました ✅ 🔧 💨 
cf. Add Heroku generated app.json https://github.com/coderdojo-japan/coderdojo.jp/commit/776f00afe7a189b8c792bee1aa91ebdba8839c08

![image](https://user-images.githubusercontent.com/155807/55385479-396e4b00-5568-11e9-8c69-55ced15ee98c.png)

**Comment by yasulab** [comment]
んー、これまだうまく動いていない...? ようなのでひとまず Re-open 💦 
cf. https://github.com/coderdojo-japan/coderdojo.jp/pull/409

**Comment by AnaTofuZ** [comment]
closeしてしまったので復旧しました。
今のところの知見をここにもまとめておきます。

原因に関しては　#409 のPRで次の様な事かなと発見しました。

- ReviewAppsでアプリケーションが作成、デプロイされる際にDB関連の初期化、seedの設定が行われていなかった
- 現在conderdojoのトップページでは、ログインした際にいくつかDojoのモデルを利用するものがある
- この中で `group_by_region` メソッドが呼ばれている箇所でエラーが発生している
- その為、 DB関連の設定をデプロイ時に設定すれば解決しそう

**Comment by AnaTofuZ** [comment]
`group_by_region` はこれ
https://github.com/coderdojo-japan/coderdojo.jp/blob/ca2b95c5582abbc947157f948e497fa1e8346f77/app/models/dojo.rb#L38

**Comment by AnaTofuZ** [comment]
試しにconsoleで使ってみたところ破滅したので、ここが原因であってそうです

```
+mumei+anatofuz$ heroku console -a coderdojo-japan-pr-446
Running console on ⬢ coderdojo-japan-pr-446... up, run.2370 (Hobby)
Loading staging environment (Rails 5.1.6.2)
irb(main):001:0> Dojo.group_by_region
D, [2019-05-15T20:04:14.804297 #4] DEBUG -- :   SQL (81.4ms)  SELECT "dojos"."id" AS t0_r0, "dojos"."name" AS t0_r1, "dojos"."email" AS t0_r2, "dojos"."order" AS t0_r3, "dojos"."description" AS t0_r4, "dojos"."logo" AS t0_r5, "dojos"."url" AS t0_r6, "dojos"."tags" AS t0_r7, "dojos"."created_at" AS t0_r8, "dojos"."updated_at" AS t0_r9, "dojos"."prefecture_id" AS t0_r10, "dojos"."is_active" AS t0_r11, "dojos"."is_private" AS t0_r12, "prefectures"."id" AS t1_r0, "prefectures"."name" AS t1_r1, "prefectures"."region" AS t1_r2 FROM "dojos" LEFT OUTER JOIN "prefectures" ON "prefectures"."id" = "dojos"."prefecture_id" ORDER BY "dojos"."prefecture_id" ASC, "dojos"."order" ASC
Traceback (most recent call last):
        4: from (irb):1
        3: from app/models/dojo.rb:39:in `group_by_region'
        2: from app/models/dojo.rb:39:in `group_by'
        1: from app/models/dojo.rb:39:in `block in group_by_region'
NoMethodError (undefined method `region' for nil:NilClass)
```

**Comment by AnaTofuZ** [comment]
`prefecture`が `nil` なのが全ての原因っぽい

```
D, [2019-05-15T20:08:31.455851 #4] DEBUG -- :   Dojo Load (3.7ms)  SELECT  "dojos".* FROM "dojos" LIMIT $1  [["LIMIT", 1]]
=> #<Dojo id: 64, name: "札幌", email: "", order: "011002", description: "北海道札幌市で月２回開催", logo: "/img/dojos/sapporo.jpg", url: "http://www.coderdojo-sapporo.jp/", tags: ["Scratch", "micro:bit", "Arduino", "ラズベリーパイ", "電子工作"], created_at: "2019-05-14 12:34:49", updated_at: "2019-05-14 12:34:49", prefecture_id: 1, is_active: true, is_private: false>
irb(main):016:0> Dojo.take.prefecture
D, [2019-05-15T20:10:17.543866 #4] DEBUG -- :   Dojo Load (5.1ms)  SELECT  "dojos".* FROM "dojos" LIMIT $1  [["LIMIT", 1]]
D, [2019-05-15T20:10:17.555794 #4] DEBUG -- :   Prefecture Load (3.9ms)  SELECT  "prefectures".* FROM "prefectures" WHERE "prefectures"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
=> nil
```

**Comment by AnaTofuZ** [comment]
こういうことらしい

```
irb(main):004:0> ActiveRecord::Base.connection.tables
=> ["prefectures", "upcoming_events", "dojos", "dojo_event_services", "event_histories", "schema_migrations", "ar_internal_metadata"]
irb(main):005:0> Prefecture
=> Prefecture(id: integer, name: string, region: string)
irb(main):006:0> Prefecture.take
D, [2019-05-15T20:30:05.813481 #4] DEBUG -- :   Prefecture Load (1.2ms)  SELECT  "prefectures".* FROM "prefectures" LIMIT $1  [["LIMIT", 1]]
=> nil
```

先ほどのコメントでもあるが、各dojoにはしっかり `prefecture_id` が降られているが、肝心のPrefecutreテーブルが作られていない模様

**Comment by AnaTofuZ** [comment]
`Prefecture` は `db/seeds.rb` で生成しているので、seedsがうまく動いていないっぽい

**Comment by AnaTofuZ** [comment]
Seedsを追加したらSELECT文で死亡する事は無くなりました
(該当commit : 49f5a4d9b8fa74f78913a5ca57334fc497b95d98)
(それで作成したherokuアプリケーションのログ: #447 )

次は画像がうまく入っていない系のエラーです。これはDBに保存していなかったような･･･
一旦どういうエラーだったかを読み込みます。

それと仕様として, reviwe appsは次の特性がある事がなんとなくわかりました
- masterではなく、PR作成時のブランチの `app.json` を参照する

**Comment by AnaTofuZ** [comment]
相変わらずasset piplineに乗ってなさそうなので、また調査する

**Comment by AnaTofuZ** [comment]
#455 で画像関連のものも解決しました。

現在はstaging環境では、assetを動的コンパイルする設定をつけており、これで解決しています。
(該当commit: c77565d705443a618f70f125a8d8632a6e7b0598)

仕様として、初回ログイン時は、動的コンパイルがおそらく走ってしまい、メモリリークでアプリケーションが開けない状態を観測しています。
その後、ある程度時間をおいて再度ログインをすることでアプリケーションは表示することが可能です。

**Comment by yasulab** [comment]
Issue 報告ありがとうございます...!! (＞人＜ )✨

**Comment by yasulab** [comment]
本 Issue は一旦解決したので、新たに見つかった課題は https://github.com/coderdojo-japan/coderdojo.jp/issues/456 に移して、本 Issue は閉じちゃいますね ;)

@AnaTofuZ 対応お疲れ様でした...!!! 👏👏👏👏👏✨
