### ISSUE TITLE
重そうなファイルを外部サービスに移行させ、Heroku Slug サイズの上限 (500MB) 以内に収めたい

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/coderdojo.jp#408]
ついに Slug の限界に到達してしまった... 😅 

```
-----> Compressing...
 !     Compiled slug size: 500.9M is too large (max is 500M).
 !     See: http://devcenter.heroku.com/articles/slug-size
 !     Push failed
```

cf. https://travis-ci.org/coderdojo-japan/coderdojo.jp/builds/512880176#L1025

## やること

- [x] どこの外部サービスを使うか決める => SoundCloud
- [x] 外部サービスと接続するコードを書く => [コメント参照](https://github.com/coderdojo-japan/coderdojo.jp/issues/408#issuecomment-480263632)
- [x] iTunes (RSS) の参照先を SoundCloud に変更する
- [ ] git リポジトリ内の mp3 ファイルを削除する
- [ ] 本番環境にデプロイする

**Comment by yasulab** [comment]
@odlovesq 現状で Heroku Slug Size ギリギリな感じなので、次はコチラをお願いできると嬉しいです (＞人＜ )✨

**Comment by yasulab** [comment]
でもどこがいいかなー、Rebuild.fm は確か S3 を使ってないって聞いたから、他のサービスの方が良いのかなぁ (SoundCloud?)

**Comment by yasulab** [comment]
> * どこの外部サービスを使うか決める

SoundCloud が良さそう...? 🎵👀✨

SoundCloud でポッドキャストをはじめる方法
https://www.gizmodo.jp/2015/07/soundcloud_podcasting.html

> SoundCloudでは、無料ユーザーでも月に3時間分アップロードできます。もしこれでは足りないという場合、55ドル/年で毎月6時間、135ドル/年で無制限にアップロード可能になりますよ。

**Comment by yasulab** [comment]
cf. soundcloud/soundcloud-ruby - Official SoundCloud API Wrapper for Ruby. 
https://github.com/soundcloud/soundcloud-ruby
https://developers.soundcloud.com

**Comment by yasulab** [comment]
@odlovesq こちらの Issue、できればちょっと早めに対策の見通しが立つと嬉しいので、一旦は @chicaco さんにお願いするカタチにしますね (＞人＜ )✨

**Comment by odlovesq** [comment]
了解です。
反応遅くてすみません…

**Comment by yasulab** [comment]
いえいえ! 全然大丈夫です! d(￣ ￣)✨

**Comment by chicaco** [comment]
soundcloud/soundcloud-ruby ですが...、
client_id, client_secret を取得すべく [Sign up for a new app](https://soundcloud.com/you/apps/new) に行ったところ、ユーザアプリの登録が停止中のようです。
ref. [Application Registration availability](https://community.soundcloud.com/share-embed-230064/application-registration-availability-7372695)

ブラウザからアクセスして Developer Tool で覗き、APP ではなくアカウントの client_id は確認できましたので(無理矢理!?)、トラック一覧取得 `GET /users/{id}/tracks` はできそうです。
が、トラック登録や更新の POST/PUT はできません。

登録はブラウザから手動で行い、API 経由で rails から利用するのは GET のみ、の方針でひとまずプロトタイプしてみます。

**Comment by chicaco** [comment]
SoundCloud の track に published_at プロパティがなさそう...

**Comment by yasulab** [comment]
`published_at` は音声データからではなくて `収録日:` から抜き出してるので大丈夫かなと思います ;)

cf. https://coderdojo.jp/podcasts/11

> 収録日: 2019/03/25

**Comment by chicaco** [comment]
> `published_at` は音声データからではなくて `収録日:` から抜き出してるので大丈夫かなと思います ;)

なるほど。そのようですね。

現 x.mp3 と x.md のセットから、mp3 だけを SoundCloud に持って行く想定です。
SoundCloud 側の track と x.md との組み合わせをどう持とうかな...、と考えているところです。

新しい mp3 コンテンツを DojoCast に公開するとき、こんなフローで大丈夫でしょうか？
(1) mp3 を準備
(2) SoundCloud に (1) で準備した mp3 を Upload (→ track の ID が決まる)
(3) CoderDojo 側の podcasts T (新設) に SoundCloud のトラックデータを取り込む。
　　rake task を想定。
　　(track id を見て、まだ登録できていないものを podcasts のレコードとして追加。
　　この際、track のプロパティから必要なものは DB に保存しておく。)
(4) podcasts のレコードの ID を使って、x.md を準備する

**Comment by chicaco** [comment]
podcasts T でなくて、sound_cloud_tracks T くらいに具体的なテーブル名がいいかしら...

**Comment by yasulab** [comment]
## 📝 MEMO: Heroku Slug Size はもうしばらくワークアラウンドで対応できそう ✅

先日僕の方で対応した Git LFS がうまく効いているみたいでだいぶ容量を削減できました! 😊 もう４〜５エピソードぐらいなら Heroku Slug Size 内で頑張れそう ;)

![image](https://user-images.githubusercontent.com/155807/56547163-879acb00-65b7-11e9-99aa-7af8b192e9fa.png)

cf. https://github.com/coderdojo-japan/coderdojo.jp/commit/9d0bd890b38911e58b5da17781a148d072b94de9

> -----> Compressing...
>        **Done: 403M**
> 
> Build log: https://travis-ci.org/coderdojo-japan/coderdojo.jp/builds/523041878#L1053-L1054

ちなみに別のワークアラウンドとしてサンプリングのHzを下げる方法もあって、これを使うとさらに小さくできることも分かりました 📉 ✨ とはいえこれは音質が下がるので、できればギリギリまで使わない方向で進めていけたらなと考えています🤔💭

**Comment by hanachin** [comment]
HerokuはGit LFSサポートしてないです

> git lfs is not supported, and using it might cause pushes to fail.
https://devcenter.heroku.com/articles/git

**Comment by hanachin** [comment]
過去のキャッシュとか含まれてる場合もあるのでこの辺雑に試してみるのはありだと思います
https://thoughtbot.com/blog/how-to-reduce-a-large-heroku-compiled-slug-size

**Comment by yasulab** [comment]
あら、Slug Size 100MB がぐらい下がったけど Git LFS じゃなかったのか 👀 💭

**Comment by yasulab** [comment]
> 過去のキャッシュとか含まれてる場合もあるのでこの辺雑に試してみるのはありだと思います
> https://thoughtbot.com/blog/how-to-reduce-a-large-heroku-compiled-slug-size

GC 試してみた! 7Mb ほど減りました ;)

> ```
> -----> Compressing...
>        Done: 396.1M
> ```

cf. https://travis-ci.org/coderdojo-japan/coderdojo.jp/builds/523730624#L1352-L1353

**Comment by chicaco** [comment]
[#431 mp3 ファイルを SoundCloud に移行する](https://github.com/coderdojo-japan/coderdojo.jp/pull/431) をマージしましたので、「外部サービスと接続するコードを書く」を済み ✅ にしました！

**Comment by yasulab** [comment]
@chicaco ご対応ありがとうございます...!! 😆 Webサイトが SoudCloud に切り替わったので少なくとも I/O 周りの負荷は今後減っていきそうです 😻🆒✨

iTunes (RSS) の参照先はまだ SoundCloud には変更されていないんでしたっけ? 🤔💭

> * [ ] iTunes (RSS) の参照先を SoundCloud に変更する
> * [ ]  git リポジトリ内の mp3 ファイルを削除する
> * [ ]  本番環境にデプロイする

**Comment by chicaco** [comment]
> iTunes (RSS) の参照先はまだ SoundCloud には変更されていないんでしたっけ? 🤔💭

RSS の URL は変更なしでしたので、iTunes で SoundCloud 側に切り換わるの待ちでした。
Apple Podcast プレビュー の [DojoCast](https://podcasts.apple.com/jp/podcast/dojocast/id1458122473) を確認したところ、現時点で既に切り換わっているようです！ ✨ 

git リポジトリ内の mp3 ファイルを削除する PR を出しますね。
