### ISSUE TITLE
CoderDojo Japan ブックの第２版向けに新しくページを作成する

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/coderdojo.jp#419]
第２版に向けてWebサイト側でも更新可能な Scrivito のページを新たに設けて欲しいとのこと。ひとまず URL 設計周りを考える。コンテンツ部分は編集者の方が用意してくれるので、外側を Scrivito で用意するところまでやれば良さそう 🤔💭 cc/ @chicaco 
cf. https://coderdojo.jp/sotechsha

![image](https://user-images.githubusercontent.com/155807/56405579-d1c63880-62a7-11e9-8f6c-12bbcfad02bb.png)

**Comment by yasulab** [comment]
いくつか考えてみましたが (`2e` とか `/2/` とか)、結局は URL の末尾に `2` を append するカタチがいいかなーという考えに落ち着きました... 😹✨ 

🤔.oO(`2e = 2nd Edition` って略式表記は日本ではあまり浸透していないし、`/2/` みたいに階層分けするほどでもないしなーという理由です)

![image](https://user-images.githubusercontent.com/155807/56861533-a4326b00-69dc-11e9-86d6-0d089d23f1b7.png)

**Comment by yasulab** [comment]
## スケジュール

> 書店での販売開始：5/23
> 課題Webサイトの作成：〆5/22

![image](https://user-images.githubusercontent.com/155807/57898328-8d708d00-7893-11e9-9c05-2263340fa72c.png)

**Comment by nanophate** [comment]
og:title 周りを整えたい。（週末にでも対応します）
https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fcoderdojo.jp%2Fsotechsha2
![image](https://user-images.githubusercontent.com/6015450/57912071-5bc3ea00-78c4-11e9-942c-105462991767.png)

**Comment by nanophate** [comment]
> og:title 周りを整えたい。（週末にでも対応します）

title の更新 Done ✅ 

![image](https://user-images.githubusercontent.com/6015450/57983186-e570e480-7a89-11e9-98ce-9289bc0bfe65.png)

**Comment by yasulab** [comment]
😻🆒✨ Thanks for tweaking OGP settings! 👍💖
