### ISSUE TITLE
routes に定義されていないパスを開くと `The page you were looking for doesn't exist.` と表示される

### ISSUE THREAD

**Issue by RyoAbe** [coderdojo-japan/coderdojo.jp#422]
routes に未定義の path（例えば  https://coderdojo.jp/aaa ）を開くと以下のように `The page you were looking for doesn't exist.` が表示れる。 `/` にリダイレクトするか、適切に404ページを出すなりしたい。

<img width="1074" alt="スクリーンショット 2019-04-20 15 44 02" src="https://user-images.githubusercontent.com/471009/56453858-4d48e800-6383-11e9-86f3-14f5b4b6e09f.png">

**Comment by yasulab** [comment]
確かに...!!!! 😹 弊社だと Ruby コミッターの yuki24 さんが作った https://github.com/yuki24/rambulance gem をよく使っているので、こういった gem を使って組み立てて行けると早く対応できそうかな考えています 🔧 💨 ✨

**Comment by yasulab** [comment]
> https://coderdojo.jp/aaa 

こちら無事に表示されることを確認しました! Issue & PR 対応ありがとうございました (＞人＜ )✨
