### ISSUE TITLE
お問い合わせフォームの左右の枠線を揃えたい

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/coderdojo.jp#440]
@megane9988 @showw 細かい調整で恐縮なんですが、『プライバシーポリシー』とその直前にある『内容』フォームの左右の枠線を縦に揃えられると嬉しいなと考えています (＞人＜ )✨ 

🤔.oO(おそらく Wufoo 側の CSS で調整する必要がありそう...?)

![image](https://user-images.githubusercontent.com/155807/57615720-56f6f180-75b7-11e9-80f0-c8f6addd78f4.png)

**Comment by showw** [comment]
![image](https://user-images.githubusercontent.com/5765654/57616917-66c40500-75ba-11e9-8758-30750922321b.png)

form.scss で ` form li ` の `padding:10px 0; ` にすると左右のラインを揃えることができそうです。

とりあえず、coderdojo.jp のローカル環境作るところからはじめます。
Readme読んで、fork 後にclone する方法でいいでしょうか？
@yasulab

**Comment by yasulab** [comment]
@showw 早速の調査ありがとうございます! 😆 先ほど CoderDojo Japan organization への Invitation mail をお送りしたので、そちらを承諾していただければ branch 間で PR できるようになると思います ;)

**Comment by showw** [comment]
あら、ローカル作ってから気づきましたが、これWooFoo側のStyleSheetsですね。（上記に安川さんが書かれてましたね 😢 失礼しました )
以前、大串さんはWooFooのアカウントに入って作業していたかと思いますが、私はやったことないのです。どうするのがよろしいでしょうか？
@yasulab @megane9988

**Comment by yasulab** [comment]
お、それでは僕の方で次のスタイル変更してみますね ;) 

> form.scss で `form li` の `padding:10px 0; ` にすると左右のラインを揃えることができそうです。

**Comment by yasulab** [comment]
@showw 先ほど確認したら https://github.com/coderdojo-japan/coderdojo.jp/blob/master/public/css/wufoo.css にあるファイルを読み込んでいるようなので、こちらの CSS ファイルをいじると調整できそうです! 

(なのでちょっと一手間かかりますが、上記ファイルを修正後コミット & デプロイして、本番環境で修正結果を確認する必要がありそうです(＞人＜;)💦)

![image](https://user-images.githubusercontent.com/155807/57620126-d2aa6b80-75c2-11e9-8bb9-465aa311fe96.png)

**Comment by yasulab** [comment]
こちら調整済みなので Close しちゃいますね! 対応ありがとうございました! (＞人＜ )✨
![image](https://user-images.githubusercontent.com/155807/84002908-293fd000-a9a4-11ea-8288-ad5d0b29d5cd.png)
