### ISSUE TITLE
CoderDojo 安曇野を集計対象に加える

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/coderdojo.jp#468]
@chicaco @Yuppymam Doorkeeper を使っている CoderDojo 安曇野が集計対象 (Stats, Events) に入ってなかったようなので、お手すきの際に当該 Dojo を集計対象に加えて頂けると助かります...!! (＞人＜ )✨

CoderDojo 安曇野
https://coderdojo-azumino.doorkeeper.jp/events/92769

[![image](https://user-images.githubusercontent.com/155807/59034398-f1d8a800-88a5-11e9-96ea-117184daa74a.png)](https://www.facebook.com/groups/coderdojo.jp/?multi_permalinks=2215469551899765&comment_id=2215792371867483)

**Comment by chicaco** [comment]
現在の CoderDojo 安曇野のイベント収集対象を確認したところ、Facebook のイベント情報ページが対象になっていました。
2018 年 3 月以降、doorkeeper の両方で参加者募集されていることが分かりましたので、まず「近日開催の道場」は doorkeeper 側から収集するよう設定を変更させていただきます。

過去イベントの履歴情報収集については、情報整理にもう少し時間がかかりそうです。
しばらくお待ちください。

**Comment by chicaco** [comment]
「近日開催の道場」ページに、CoderDojo 安曇野のイベントも掲載できました。

![0607_1](https://user-images.githubusercontent.com/1582945/59074947-fa15ff00-8908-11e9-9095-002e62bcd6b0.png)

**Comment by yasulab** [comment]
対応ありがとうございます! 😆🎉✨ Close しますね ;)

**Comment by yasulab** [comment]
> 過去イベントの履歴情報収集については、情報整理にもう少し時間がかかりそうです。
> しばらくお待ちください。

あ、こちらはまだ対応してなかったですね... >< 💦 Re-open します!
