### ISSUE TITLE
CoderDojo 豊橋を集計対象に加えたい

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/coderdojo.jp#472]
@Yuppymam (＞人＜ )✨

cf. https://www.facebook.com/groups/coderdojo.jp/2215469551899765/?comment_id=2217161735063880

[![image](https://user-images.githubusercontent.com/155807/59090461-cc03df80-8947-11e9-86ef-4503248799ea.png)](https://www.facebook.com/groups/coderdojo.jp/2215469551899765/?comment_id=2217161735063880)

**Comment by chicaco** [comment]
Doorkeeper API 経由でイベント情報を取得しているのですが、開催期間を指定したとき開催初日の条件指定になってしまうようです。
6月分が掲載されていないのは、ご推察の通り複数回分をまとめているためと思われます。
対応についてもう少し検討させてください。

**Comment by chicaco** [comment]
終了日が本日以降のイベントを表示するよう修正しました。

<img width="608" alt="20190618_toyohashi" src="https://user-images.githubusercontent.com/1582945/59617019-81147400-9160-11e9-8343-9890b11d7772.png">
