### ISSUE TITLE
📅 近日開催の道場のデザインを改善したい 🎨👨‍🎨

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/coderdojo.jp#474]
@showw [近日開催の道場](https://coderdojo.jp/events)が結構好評なので、現状より見やすいデザインにしたいなと考えています🤔💭✨ cc/ @megane9988 

ひとまずリリースを念頭にしていて、デザインを後回しにしていましたが、思いのほか好評だったのでデザインも改善したい... 🎨👨‍🎨

cf. [📜 User Success Story #258](https://github.com/coderdojo-japan/coderdojo.jp/issues/258)

ちなみにモバイル版からのアクセスが多いので、PC版だけでなくモバイル版からも視認しやすいデザインだといいなと考えています 📱 💻 ✨ 

### 横幅が大きいとき

![image](https://user-images.githubusercontent.com/155807/59137466-fe9eee00-89c2-11e9-94f3-fdb0137a39f8.png)

### モバイル版

![image](https://user-images.githubusercontent.com/155807/59137541-46257a00-89c3-11e9-9423-5dcf868db424.png)

**Comment by showw** [comment]
ローカルを立ち上げてイベントページを見ると、開催情報が表示されない状況です。
何か足りていない手順があれば、お教えいただけますか。

![image](https://user-images.githubusercontent.com/5765654/59640478-7b1d9380-915e-11e9-95de-53794f6032da.png)

そしてすみません、今週あまり進捗をあげられず、申し訳ないです...

**Comment by chicaco** [comment]
以下の手順でレコードを入れてください。

### (1) dojo を追加

`bundle exec rails dojos:update_db_by_yaml` を実行

### (2) dojo_event_service を追加

`bundle exec rails dojo_event_services:upsert` を実行

### (3) upcomint_event を追加

`bundle exec rails upcoming_events:aggregation` を実行

これで dojo 情報と dojo_event_service 情報が update され、upcoming_event (近日開催情報) を取得して DB に保存します！

**Comment by showw** [comment]
上記の手順を試してみました。
(1)と(2)は問題なくできましたが、(3)を実行したときに以下のようになります。

```
$ bundle exec rails dojos:update_db_by_yaml
$ bundle exec rails dojo_event_services:upsert
Deleted: 0
Updated: 0
Inserted: 0
$ bundle exec rails upcoming_events:aggregation
UpcomingEvents aggregate
Aggregate of connpass
```

ここでとまってしまう。

Ctrl+Cで止めると、

```
^Crails aborted!
Interrupt:
/Users/shoko/GoogleDrive/htdocs/coderdojo.jp/lib/event_service/client.rb:11:in `get'
/Users/shoko/GoogleDrive/htdocs/coderdojo.jp/lib/event_service/providers/connpass.rb:36:in `block (2 levels) in fetch_events'
/Users/shoko/GoogleDrive/htdocs/coderdojo.jp/lib/event_service/providers/connpass.rb:35:in `loop'
/Users/shoko/GoogleDrive/htdocs/coderdojo.jp/lib/event_service/providers/connpass.rb:35:in `block in fetch_events'
/Users/shoko/GoogleDrive/htdocs/coderdojo.jp/lib/event_service/providers/connpass.rb:34:in `each'
/Users/shoko/GoogleDrive/htdocs/coderdojo.jp/lib/event_service/providers/connpass.rb:34:in `fetch_events'
/Users/shoko/GoogleDrive/htdocs/coderdojo.jp/lib/upcoming_events/tasks/connpass.rb:13:in `block (2 levels) in run'
/Users/shoko/GoogleDrive/htdocs/coderdojo.jp/lib/upcoming_events/tasks/connpass.rb:12:in `block in run'
/Users/shoko/GoogleDrive/htdocs/coderdojo.jp/lib/upcoming_events/tasks/connpass.rb:11:in `each'
/Users/shoko/GoogleDrive/htdocs/coderdojo.jp/lib/upcoming_events/tasks/connpass.rb:11:in `run'
/Users/shoko/GoogleDrive/htdocs/coderdojo.jp/lib/upcoming_events/aggregation.rb:56:in `block in execute'
/Users/shoko/GoogleDrive/htdocs/coderdojo.jp/lib/upcoming_events/aggregation.rb:54:in `each'
/Users/shoko/GoogleDrive/htdocs/coderdojo.jp/lib/upcoming_events/aggregation.rb:54:in `execute'
/Users/shoko/GoogleDrive/htdocs/coderdojo.jp/lib/upcoming_events/aggregation.rb:17:in `block in run'
/Users/shoko/GoogleDrive/htdocs/coderdojo.jp/lib/upcoming_events/aggregation.rb:42:in `with_notifying'
/Users/shoko/GoogleDrive/htdocs/coderdojo.jp/lib/upcoming_events/aggregation.rb:15:in `run'
/Users/shoko/GoogleDrive/htdocs/coderdojo.jp/lib/tasks/upcoming_events.rake:7:in `block (3 levels) in <top (required)>'
/Users/shoko/GoogleDrive/htdocs/coderdojo.jp/lib/tasks/upcoming_events.rake:6:in `block (2 levels) in <top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => upcoming_events:aggregation
(See full trace by running task with --trace)
ShokonoMacBook-Pro:coderdojo.jp shoko$
```
という状態です。

**Comment by Yuppymam** [comment]
`Aggregate of connpass`、結構時間かかるので少し待ってみると、`Aggregate of doorkeeper`が表示されませんか？？😊
止まっている時の画面にエラー画面は出ていますか？

**Comment by Yuppymam** [comment]
あとPostgresを起動しておかないとダメかもしれません！💦
`pg_ctl -D /usr/local/var/postgres start`で起動します！

**Comment by chicaco** [comment]
コメントいただいているように、`Aggregate of connpass` は時間がかかります。長くても2,3分と思いますが。

もう一点、お伝えできていなかったのですが、環境変数 `DOORKEEPER_API_TOKEN` の設定が必要です。

> Doorkeeper のイベントを取得するためには、下記ページから Doorkeeper API Token を取得し、環境変数 DOORKEEPER_API_TOKEN に設定してください。
> https://manage.doorkeeper.jp/user/oauth/applications

申し訳ありません。 🙇‍♀ 
./bin/setup だけで構築できるよう、[#491 ./bin/setup タスクで Dojo 関連のレコードもまとめて作成してしまう?](https://github.com/coderdojo-japan/coderdojo.jp/issues/491) で対応中なのですが、間に合っておりません。 🙏

**Comment by showw** [comment]
ご返信ありがとうございます。

>./bin/setup だけで構築できるよう、#491 ./bin/setup タスクで Dojo 関連のレコードもまとめて作成してしまう? で対応中なのですが、間に合っておりません。

急がせてしまったようで、すみません。
実は私、今週はWordCamp参加のため、あまり作業がすすみそうにないという事情もあり、:sweat_drops:
とりあえず #491 が終わってから取り掛かることにしますね。

**Comment by chicaco** [comment]
お待たせしております。
[#491 ./bin/setup タスクで Dojo 関連のレコードもまとめて作成してしまう?](https://github.com/coderdojo-japan/coderdojo.jp/issues/491) への対応が完了しました。

環境変数 `DOORKEEPER_API_TOKEN` が設定されていない場合、Doorkeeper からの収集は行わず、connpass からのみ収集するよう処理しております。

問題があればお知らせください！

**Comment by showw** [comment]
現在の「近日開催の道場」は、文字だけのリストになっていますが、可能でしたらトップページの道場一覧のレイアウトに揃えて、各道場のロゴを載せて、このようなレイアウトにするのはいかがでしょうか。
県内で１件しかない場合、中央寄せになってしまいますが。

一番目立たせたいのは、日付と時間のところですので、背景をdojoカラーの青にして、視認性が良くなるようにしています。
（現段階ではコードは触っていません）

![image](https://user-images.githubusercontent.com/5765654/61505836-24d09880-aa1b-11e9-899b-449261f3d26a.png)

@chicaco @yasulab

**Comment by chicaco** [comment]
視認性も 🆙 して、よさそうですね。

レアケースなのですが、複数の Dojo で 1 つのイベント管理プロバイダ(connpass, doorkeeper など)を共有しているところ(例 : 奈良・生駒・田原本)があり、Dojo が一意にならないのでロゴが決まりません。
独自ロゴがない Dojo と同様に、デフォルトのロゴを使うようにすればよいでしょうか。

**Comment by yasulab** [comment]
> Dojo が一意にならないのでロゴが決まりません

ロゴを外したデザイン案があれば話は早く進みそうですね 😉  ロゴが必須なデザイン案になると @chicaco さんのおっしゃるような状況が発生し、開発が止まってしまうので 👀 💭

**Comment by yasulab** [comment]
> Dojo が一意にならないのでロゴが決まりません

@showw ロゴを外したデザイン案があれば話は早く進みそうですね 😉  ロゴが必須なデザイン案になると @chicaco さんのおっしゃるような状況が発生し、開発が止まってしまうので 👀 💭

**Comment by showw** [comment]
>@showw ロゴを外したデザイン案があれば話は早く進みそうですね

了解です。このレイアウトで、ロゴを外した形ですすめたいのですが......
私がhamlをあまり理解していないため、実装するのに時間がかかってしまいそうです 😓 
もし可能であれば、 @chicaco  さんの方でざっくりコーディングしてもらい、そのあと私に引き継いでCSSで整える、という形にしてもらえると早めに進められると考えていますが、いかがでしょうか？
@yasulab

**Comment by showw** [comment]
![image](https://user-images.githubusercontent.com/5765654/61510101-7d5c6180-aa2c-11e9-841a-b69cdd139529.png)

**Comment by chicaco** [comment]
@showw 承知しました！
PR作成してブランチを切り、ベースになるコードを書いてみますね。 💪 
しばしお待ちを...

**Comment by chicaco** [comment]
@showw 
PR #502 を起票しました。
upcoming_events_design_renewal ブランチのコードをベースにしていただければ！

申し送り事項を #502 のコメントに記載していますので、ご確認ください。

ここで引き継がせていただいてよろしいでしょうか？
不明点や相談ごとなどございましたら、ご遠慮なくお声掛けください。

**Comment by showw** [comment]
@chicaco ありがとうございます、
#502 でプルリクを送っておりますので、ご確認ください。

**Comment by showw** [comment]
#502 がマージされましたので、このissueはcloseします。
