### ISSUE TITLE
CoderDojo 日進を集計対象に追加したい

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/coderdojo.jp#475]
@Yuppymam (＞人＜ )✨

cf. https://www.facebook.com/groups/coderdojo.jp/permalink/2215469551899765/?comment_id=2218719781574742

[![image](https://user-images.githubusercontent.com/155807/59144115-b2c56680-8a0d-11e9-981e-d28f1a341177.png)](https://www.facebook.com/groups/coderdojo.jp/permalink/2215469551899765/?comment_id=2218719781574742)

**Comment by Yuppymam** [comment]
確認したところ、dojo_event_services.yaml に connpass のURLが追加されていませんでしたので、追加してプルリクを出した後に @chicaco さんに動作確認してもらいたいと思います😊
反映まで、少々お待ちください🙏
