### ISSUE TITLE
CoderDojo 港北NTを集計対象に追加したい

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/coderdojo.jp#477]
@Yuppymam (＞人＜ )✨

cf. https://twitter.com/KY17763521/status/1136966080490905601

[![image](https://user-images.githubusercontent.com/155807/59154257-1cdf1980-8aa9-11e9-990e-952c4bdf3de9.png)](https://twitter.com/KY17763521/status/1136966080490905601)

**Comment by kasuyaSansan** [comment]
すみません💦
そう言えばやってなかった！と思ったらやってもらっていました

**Comment by yasulab** [comment]
d(￣ ￣)✨
