### ISSUE TITLE
ソーテック社の本に「本章の詳細」リンクを追加したい

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/coderdojo.jp#480]
第２版のページでは、初版にあった次の文言が抜けていました... >< 💦 cc/ @nanophate 

> 本ページでは、上記の書籍内で利用する素材や、課題の答えを掲載しています。
> (本書の詳細は[コチラ](http://www.sotechsha.co.jp/pc/html/1151.htm)へ)

## 初版: https://coderdojo.jp/sotechsha

![image](https://user-images.githubusercontent.com/155807/59160458-15ebf180-8b11-11e9-9a45-a6e3f4988c62.png)

## 第２版: https://coderdojo.jp/sotechsha2

![image](https://user-images.githubusercontent.com/155807/59160448-fd7bd700-8b10-11e9-8617-21979c6f690c.png)

**Comment by nanophate** [comment]
Scrrivito で編集や追加ができる部分だったので、対応しました。
https://coderdojo.jp/sotechsha2/ から確認よろしくお願いします。:bow:
<img width="597" alt="image" src="https://user-images.githubusercontent.com/6015450/59160658-3cab2780-8b13-11e9-9558-19bb8cb6edb7.png">

**Comment by nanophate** [comment]
@yasulab http://www.sotechsha.co.jp/pc/html/1238.htm にリンク先を指定しました。
なにか修正する必要がある場合は、coderdojo.jp/login からログインして変更できます。

**Comment by yasulab** [comment]
確認しました! ✅ 対応ありがとうございました!! 😸✨
