### ISSUE TITLE
dojos:update_db_by_yaml タスク内で、既存の dojos_id_seq の最大値を取得してセットする処理を入れたい

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/coderdojo.jp#484]
@nalabjp 一から環境構築すると下記のようなエラーに遭遇することが多くなったのと、僕以外の人でも Dojo を追加できるような体制に移行したいので、標題のような処理が入ると良いかなぁと思ったんですがいかがでしょう...?  🤔💭 cc/ @chicaco @Yuppymam 

📜 参考: PostgreSQL の Auto Incremental ID を初期化する方法 - GitHub
https://github.com/coderdojo-japan/coderdojo.jp/blob/master/docs/how-to-update-db-id.md

**Comment by chicaco** [comment]
[#412 Dojo 掲載フォームを Google Form から Rails に移行する](https://github.com/coderdojo-japan/coderdojo.jp/issues/412) が実現できれば、この問題も解決できるかな、と思いました。
次に #412 に着手しようと考えていたところです。

**Comment by yasulab** [comment]
> 次に #412 に着手しようと考えていたところです。

#412 もいずれ着手したいとは考えていますが、本 Issue の目的であるところの、

> 僕以外の人でも Dojo を追加できるような体制に移行したい

を #412 経由で実現するために必要な工数はそこそこ大きそうなので、まずは小さい工数で目的を実現できる最小単位のタスクを優先的に勧められたらなと考えています 😉

**Comment by nalabjp** [comment]
https://github.com/rails/rails/blob/63ace8fc9e4b6ae19a80b508d029bf37072a0fe9/activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb#L273-L299

ARに実装があるのでそれを使うのが良さそうですかね。
