### ISSUE TITLE
./bin/setup タスクで Dojo 関連のレコードもまとめて作成してしまう?

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/coderdojo.jp#491]
@chicaco それぞれのタスクは冪等性が担保されているかなと思うので、次のタスクも `./bin/setup` にまとめてしまうと「[(レコードがないことにより) ooo が表示できない](https://github.com/coderdojo-japan/coderdojo.jp/issues/474#issuecomment-502872907)」系の質問にまとめて対応できるようになって楽かなと思いましたが、いかがでしょう? 🤔💭

> 以下の手順でレコードを入れてください。
> 
> ### (1) dojo を追加
> 
> `bundle exec rails dojos:update_db_by_yaml` を実行
> 
> ### (2) dojo_event_service を追加
> 
> `bundle exec rails dojo_event_services:upsert` を実行
> 
> ### (3) upcomint_event を追加
> 
> `bundle exec rails upcoming_events:aggregation` を実行
> 
> これで dojo 情報と dojo_event_service 情報が update され、upcoming_event (近日開催情報) を取得して DB に保存します！

_Originally posted by @chicaco in https://github.com/coderdojo-japan/coderdojo.jp/issues/474#issuecomment-502895577_

**Comment by yasulab** [comment]
@chicaco それぞれのタスクは冪等性が担保されていると思うので、上記 Description で書いたようなタスクも `./bin/setup` にまとめてしまうと「(レコードがないことにより) ooo が表示できない」系の質問にまとめて対応できるようになって楽かなと思いましたが、いかがでしょう? 🤔💭

**Comment by chicaco** [comment]
よさそうですね。
`rails upcoming_events:aggregation` は `./bin/setup` に入れたいです。
環境変数 DOORKEEPER_API_TOKEN を設定する必要がありますが、これはどこに何を追記しておけばよいでしょうか？
(このあたりのお作法に疎くて済みません 🙇‍♀ )

もうひとつ、統計情報用の過去履歴収集の `rails statistics:aggregation[from,to]` も `./bin/setup` に入れた方がよいでしょうか？
全統計情報となると 2012年～ の期間で収集する必要があり、数分かかることもあります。

**Comment by yasulab** [comment]
> 環境変数 DOORKEEPER_API_TOKEN を設定する必要があります

あー、なるほど。DOORKEEPER API TOKEN は誰のでも良いはずなので、ひとまずはご自身の Doorkeeper アカウントから https://manage.doorkeeper.jp/user/oauth/applications にアクセスし、そこで生成したトークンを設定してもらうと良いかなと考えています ;) 

bin/setup タスクとしては、DOORKEEPER_API_TOKEN があるかないかを判断し、もしなければ Doorkeeper API を叩かずに、

> 環境変数 `DOORKEEPER_API_TOKEN` がなかったため、
> Doorkeeper API の取得をスキップしました。
> Doorkeeper のイベントを取得するためには、
> Doorkeeper のアカウントでログイン後、下記ページから
> API Token を取得して環境変数 `DOORKEEPER_API_TOKEN` に設定してください
> https://manage.doorkeeper.jp/user/oauth/applications

みたいな標準出力をしておくと親切そうかなと思いました ;)

**Comment by yasulab** [comment]
> 全統計情報となると 2012年～ の期間で収集する必要があり、数分かかることもあります。

やりたいことは開発環境のセットアップで、本番環境と同じ全統計情報を揃える必要はないと思うので、例えば、デフォルトでは直近３ヶ月のデータのみを取得するというのはいかがでしょうか? 😆✨

**Comment by chicaco** [comment]
DOORKEEPER_API_TOKEN の件、よいアイディアをありがとうございます。

標準出力に出すメッセージには、以下も追記しますね。

```
環境変数 DOORKEEPER_API_TOKEN を設定した後で、
`bundle exec rails upcoming_events:aggregation[doorkeeper]` を実行してください。
```

あ、`bin/setup` を再実行でもよいのでしょうか？
繰り返し実行しても問題なければ `bin/setup` 再実行の方がシンプルですね。

**Comment by yasulab** [comment]
> あ、`bin/setup` を再実行でもよいのでしょうか？

現時点での `./bin/setup` は冪等性が担保されていたはずなので、これから追加するタスクの冪等性も同様に担保されていれば、何度実行されても大丈夫かなと思います ;)

**Comment by chicaco** [comment]
> やりたいことは開発環境のセットアップで、本番環境と同じ全統計情報を揃える必要はないと思うので、例えば、デフォルトでは直近３ヶ月のデータのみを取得するというのはいかがでしょうか? 😆✨

確かに、統計情報のページ自体を修正したりするのでなければ、全統計情報は不要ですね。
デフォルトで直近 3 ヶ月だけを取得するように、`bin/setup` に書きますね。

こちらも DOORKEEPER_API_TOKEN は必要なので、標準出力に出すメッセージはこれも考慮した内容にします。

**Comment by yasulab** [comment]
😻🆒✨

**Comment by chicaco** [comment]
> 現時点での ./bin/setup は冪等性が担保されていたはずなので、これから追加するタスクの冪等性も同様に担保されていれば、何度実行されても大丈夫かなと思います ;)

承知しました！
`rails upcoming_events:aggregation` も `rails statistics:aggregation[from,to]` も冪等性は担保できていますので、DOORKEEPER_API_TOKEN を設定後に `./bin/setup` を実行する、という手順でメッセージに出力しましょう。

**Comment by yasulab** [comment]
🆒 d(￣ ￣)✨

**Comment by chicaco** [comment]
📝 `rake soundcloud_tracks:upsert` も `./bin/setup` に追加した方がよさそう。
環境変数 `SOUNDCLOUD_CLIENT_ID` の設定が必要。
`SOUNDCLOUD_USER_ID` は固定にしてよいので、修正する。

**Comment by yasulab** [comment]
> 📝 `rake soundcloud_tracks:upsert` も `./bin/setup` に追加した方がよさそう。

SoundCloud は開発する人が増えるとは想像しにくいので、そのときになったらまた考えましょう ;) 

cf. YAGNI - Wikipedia
https://ja.wikipedia.org/wiki/YAGNI

> "You ain't gonna need it"、縮めて YAGNI とは、機能は実際に必要となるまでは追加しないのがよいとする、エクストリーム・プログラミングにおける原則である。
> 
> 後で使うだろうという予測の元に作ったものは、実際には10%程度しか使われない。したがって、それに費やした時間の90%は無駄になる。

**Comment by chicaco** [comment]
> SoundCloud は開発する人が増えるとは想像しにくいので、そのときになったらまた考えましょう ;)

了解です。

[#458 DojoCast から "収録日: yyyy/MM/DD" を削除したい](https://github.com/coderdojo-japan/coderdojo.jp/issues/458) に対応していただくので、こちら個別にフォローします！

**Comment by yasulab** [comment]
ありがとうございます...!! よろしくお願いします 😆✨

**Comment by chicaco** [comment]
現実装の動確をすべく、新しく git clone して `bin/setup` してみたところ以下のエラーになりました。

```
　:
== Preparing database ==
Could not find net-http-pipeline-1.0.1 in any of the sources
Run `bundle install` to install missing gems.

== Command ["bin/rails db:setup"] failed ==
```

bundle install すると、
```
Using net-http-persistent 3.0.0
Using net-http-pipeline 1.0.1
```
と表示はされるんですが、エラーが解消できません。
```
> bin/rails db:setup
Could not find net-http-pipeline-1.0.1 in any of the sources
Run `bundle install` to install missing gems.
```

まずこちらを解決せねば...。

**Comment by chicaco** [comment]
gem を一旦クリアして `bundle install` し直したら、エラーは解消しました。
