### ISSUE TITLE
CoderDojo 福岡の過去イベント実施分を集計したい

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/coderdojo.jp#503]
@Yuppymam @chicaco 

CoderDojo 福岡が Facebook イベントから connpass 利用に切り替えたので、過去のイベント実施分を追加していただけると助かります (＞人＜ )✨

- Facebook Events: https://www.facebook.com/pg/CoderDojoFukuoka/events/
   - 第１回〜第３回は Facebook Events のみなので、ここから集計
- connpass Events: https://coderdojo-fukuoka.connpass.com/event/
   - 第４回以降は connpass にもあるので、connpass で集計する

-----

<div>
<span><img src="https://avatars1.githubusercontent.com/u/155807?v=4" width="16" height="16" alt="" /></span>
<a href='https://github.com/yasulab'>yasulab</a>
pushed to
<a href='https://github.com/coderdojo-japan/coderdojo.jp/tree/master'>master</a>
at
<a href='https://github.com/coderdojo-japan/coderdojo.jp'>coderdojo-japan/coderdojo.jp</a>
(<a href='https://github.com/coderdojo-japan/coderdojo.jp/compare/8b828e43fa56...2f40d091b1ed'>compare</a>)
</div>
<ul>
<li>
<a href='https://github.com/coderdojo-japan/coderdojo.jp/commit/2f40d091b1ed2e5858332752bc511df262820cf9'><tt>2f40d09</tt></a>
Change CoderDojo 福岡 event service: Fb -&gt; connpass

</li>
</ul>

**Comment by Yuppymam** [comment]
昨夜ちょうど7月分の Facebook イベント集計をやっていて、まだ途中なのでまとめてやってしまいますね📑👌

**Comment by yasulab** [comment]
よろしくお願いします...!! (＞人＜ )💖✨

**Comment by Yuppymam** [comment]
具体的な作業内容の確認ですが
- 第１回〜第３回までの facebook_event は残して、第４回以降は facebook_event から削除 ✂️ 
- dojo_event_services の url を connpass に変更
で宜しいですか😊？

**Comment by chicaco** [comment]
#508 デプロイ後、2018/01 以降のイベントを再収集しましたので、対応完了です！
