### ISSUE TITLE
Dojoを指定して統計情報を収集したい

### ISSUE THREAD

**Issue by chicaco** [coderdojo-japan/coderdojo.jp#507]
## 背景

既存の Dojo を新たに統計情報収集対象に追加するときなど、特定の Dojo の統計情報を追加収集したいが、現状では期間とプロバイダの指定しかできない。収集済みの他の Dojo の統計情報は再収集する必要がないのでその状態をキープしたまま、指定した Dojo の統計情報のみ収集できると効率がよい。

## やりたいこと

Dojo を指定して統計情報を収集したい。

**Comment by yasulab** [comment]
良さそう 👀✨
