### ISSUE TITLE
CoderDojo の表示順序を追加する流れを定式化する

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/coderdojo.jp#58]
## 現状

Dojoモデルのorderカラムにyasulabが手動で順序情報を **適当に** 入力している。適当に入力すると自動化が困難なため、入力する値を定式化したい。

## 当初のアイデア

多分こんな感じ...? 🤔

1. 全国の CoderDojo を都道府県 (北海道→...→東京→...沖縄) でソート
2. 各都道府県内では latitude 順 (沖縄県なら嘉手納→那覇→宮古島) でソート
3. ソートした結果を yaml ファイルに書き出す

cf. https://github.com/yasslab/coderdojo.jp/compare/30f878648e3e...4f2601f86619

## 最終的な実装案

> ## 市町村コード順
> 総務省が市町村コードを発行しているらしいです
> http://www.soumu.go.jp/denshijiti/code.html

cf. https://github.com/coderdojo-japan/coderdojo.jp/issues/58#issuecomment-350717763

**Comment by yasulab** [comment]
## @siman-man さんからの助言 (Thx! 😸 ✨ )

> 自分も安川さんの実装案とほぼ一緒でした。
>  今のyaml情報に都道府県コードと緯度情報を追加してそれをキーにsort_byして並べ替える感じです
> 
> ```rb
> dojo_list.sort_by{|dojo| [dojo[:order], dojo[:latitude]] }
> ```

**Comment by yasulab** [comment]
8地方区分と都道府県のソート順は、ここら辺が参考になりそう🤔

日本のCoderDojo（zen登録済）- Google Spreadsheet
https://docs.google.com/spreadsheets/d/17-M-qv5c0MdE_ZIFk566I2CGCIDHFkQwXWiunDXCGVw/edit#gid=354377216

**Comment by katzueno** [comment]
お世話になります。

さきほど、安川さんに CoderDojo.jp のリスティングに、CoderDojo 尾張を追加していただきました。安川さん、ありがとうございます！

しかし、なんかちょっと違和感を感じました。自分の Dojo の場所が探しにくかったです。
そして、その違和感は、表示順かな・・・と。

都道府県の順番が決まっているように、地元でも市区町村の表示順が決まっていると思うのですが、.jp 上のサイトは、その順番に準じていなかったので、探しづらかったのかと思います。

参考になるのが、天気予報の表示順かなと・・・
例えば愛知県がこちら。
http://www3.nhk.or.jp/weather/caution_23.html
こちらの順番にそって表示すると

・名古屋
・天白
・尾張
・大治
・豊橋

という順番で良いかなとも思いました。

そしていろいろ調べてみるとありましたね・・・。

# 表示順提案

## 郵便番号順

開催地の郵便番号で並び替えする。
これが一番良いのではないでしょうか。
開催 Dojo の郵便番号を入れて、それで Sort する。

## 天気予報の注意報・警報表示順

個人的に気象予報区の区分が良いと考えています。
なぜかというと、みんなは天気予報を毎日みているので、その表示順に慣れている人が多いから。
ただ、CSV などわかりやすいデータにはないっていないですね・・・。
http://www.jma.go.jp/jma/kishou/know/saibun/

## 電話番号市外局番順

開催地の電話番号順で並び替えする
ただ電話番号は公開しない人もいますし、
登録をしなければいけない手間は増えます。

## 市町村コード順

総務省が市町村コードを発行しているらしいです
http://www.soumu.go.jp/denshijiti/code.html
これでも良いですが、追加入力の手間は同じですね。


以上、個人的には、郵便番号でのソートが総合的に良いのではと思います。
UX を考えると天気予報が一番なんですが・・・。

**Comment by yasulab** [comment]
> 開催地の郵便番号で並び替えする。

郵便番号は面白そうですね〜。１点気になったところは、開催場所が固定されていない Dojo もあり、必ずしも郵便番号の範囲内で開催されているとは限らない点（なのでDojo運営者がどの郵便番号を入力すればいいか迷いそうな点）が少し気になりました🤔

とはいえ、やってみて問題があれば都度修正したり、最悪revertする形で対応できそうなので、まずは郵便番号で試してみても良さそうですね🔧

**Comment by yasulab** [comment]
🤔(自動化する方法としては、Zen上にあるDojo情報からわかりやすい表示順にコンバートするやり方とかかなぁ)

**Comment by hanachin** [comment]
第1ソートキーは都道府県コード、第2ソートキーは電話帳同様CoderDojoの名前の五十音順にするのはどうでしょうか
https://ja.wikipedia.org/wiki/五十音順

五十音順だとソートするとき各都道府県内での開催場所を考慮する必要がなさそう

**Comment by yasulab** [comment]
> 都道府県の順番が決まっているように、地元でも市区町村の表示順が決まっていると思うのですが、.jp 上のサイトは、その順番に準じていなかったので、探しづらかったのかと思います。

katzさんの課題意識としては、第２ソートキーも「天気予報などで一般的によく見られる順序でソートされていて欲しい」とのことなので、名前順が一般的によく見られる順序かどうか、という点がポイントになりそうかなぁ🤔

**Comment by katzueno** [comment]
一番の優先事項は誰でもメンテしやすい形にするのが一番だとおもうので。

あ、あと、別 Issue 立てるべきかもですが、
Zen の Map を何らかの形で Japan の地図の絞込表示の埋め込みできると良いかもですね。

**Comment by yasulab** [comment]
> Zen の Map を何らかの形で Japan の地図の絞込表示の埋め込みできると良いかもですね。

Foundationからは「alpha版だから本番利用はちょっと待って」とは言われてますが、一応こちらの Issue に外部サイトから利用する手順をまとめています ;) 🌍 

トップページにCoderDojo Mapを埋め込む
https://github.com/coderdojo-japan/coderdojo.jp/issues/32

**Comment by katzueno** [comment]
すいません。
全部の issue を確認しきれてなくて orz

**Comment by yasulab** [comment]
いえいえ! 結構いろんな Issue があるので、知ってくれる人が増えるのは嬉しい限りです 😸

**Comment by yasulab** [comment]
@katzueno #223 でソート順を変更してみました! 並び順、いかがですかね? 🤔💭

CoderDojo Japan
https://coderdojo.jp/#dojos

いくつか案をいただきましたが、最終的には order カラムを自動的に追加できるようにしたかったので、今回は katz さんの次の案を採用してみました 😸✨ 

> ## 市町村コード順
> 
> 総務省が市町村コードを発行しているらしいです
> http://www.soumu.go.jp/denshijiti/code.html
> これでも良いですが、追加入力の手間は同じですね。

[全国地方公共団体コードを Google Spreadsheet に載せた](https://docs.google.com/spreadsheets/d/1b2XZxifpP8GSASvP9sPq1BYwsCH6Y_FHSkol_nfaGxw/edit?usp=sharing)ので、いずれは表を lookup して自動で order の値を見つけられるようにしたいなと考えています 🤖💨

**Comment by katzueno** [comment]
@yasulab お疲れ様でした！ありがとうございます。

**Comment by nalabjp** [comment]
orderの自動化は #228 を起こしたのでこちらは一旦クローズします〜

**Comment by yasulab** [comment]
対応ありがとうございます! 😸 続きは #228 でやりましょ〜 🏃💨
