### ISSUE TITLE
📊 連名で登録されている Dojo も統計情報で集計できるようにしたい

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/coderdojo.jp#610]
(読んで欲しい人: @Yuppymam @chicaco )

coderdojo.jp には２つ以上の Dojo が連名で登録しているケースがありますが、現状では、[統計情報](https://coderdojo.jp/stats)としては１つの Dojo としてカウントされています 👀📊

![image](https://user-images.githubusercontent.com/155807/66813696-2e14c700-ef70-11e9-98a1-776b5b768ac1.png)

例えば上記の場合、Dojo 数としては 4 Dojos として集計できるとより正確になるので、次の２点について適切な設計を行い、より正確な統計情報が出せるようになると良いなと考えています 👀💭✨

(前々から改善したいなぁとは思いつつ、うまい解決方法が思い浮かばなかったのですが、ちょっと良さそうなアイデアを思いついたので Issue として共有しますね 😉 )

## 1. データベース設計
実現方法は色々ありそうですが、まずは情報を整理して設計する必要がありそうです。

- A. Dojo に counter カラム (Default: 1) を追加する
   * 統計情報ページなどで `Dojo.count` を使っているはずなので、それらのコードを新カラムを使って計測するように書き換える
   * `Dojo.count`の count メソッドと見分けやすくするため `counter` カラムにしています
- B. Dojo モデルの上位概念を作る?
   - 上位概念 has_many Dojos
   - 上位概念を、後述のデザイン設計とともに coderdojo.jp で表示する

他にも色々やり方はありそうですが、データベース設計は情報を整理すれば大丈夫そうなイメージです 👀💭

## 2. デザイン設計
**誰でも Dojo 数を検証できる状態を維持したまま、** より正確な統計情報にしたい。例えば「rails console を叩かないとデータを検証できない」といった状態は避けたいです。

これはデザインで解決できそうだと思っていて、例えば iOS のバッジのような形で表現することはできそうかなと考えています 👨‍🎨💭  (２つ以上の連名 Dojo の場合はバッジが表示され、連名している Dojo 数がバッジで表示される。**coderdojo.jp にある Dojo 数とバッジの値を計算すれば誰でも検証できる。** )

![IMG_4895](https://user-images.githubusercontent.com/155807/66814450-91532900-ef71-11e9-9f6a-8572e2fbe4bf.jpg)

👀 .oO(on-mouse で  `"#{badge_number} つの Dojo を１つとして掲載しています` みたいな Tooltip を表示すると良さそう?)

## 連名で掲載している Dojo

連名 Dojo は２つとは限らなくて、例えば「[CoderDojo しまね](https://github.com/smalruby/smalruby.jp/wiki/道場のフォーム)」は７つの Dojo (松江、雲南、大田、江津、邑南、浜田、益田) の連名となっています。

[![image](https://user-images.githubusercontent.com/155807/85091568-a1b75400-b222-11ea-9dfd-3f0d999d6ad2.png)](https://github.com/smalruby/smalruby.jp/wiki/%E9%81%93%E5%A0%B4%E3%81%AE%E3%83%95%E3%82%A9%E3%83%BC%E3%83%A0)

cf. https://github.com/smalruby/smalruby.jp/wiki/%E9%81%93%E5%A0%B4%E3%81%AE%E3%83%95%E3%82%A9%E3%83%BC%E3%83%A0

**Comment by Yuppymam** [comment]
こちら、 @chicaco さんにデータベース設計をお願いしたいです🙏💦（見ながら勉強したいです）
デザインの方は挑戦したいです🙋‍♀️✨

**Comment by yasulab** [comment]
@chicaco おはようございます！先日お伝えし忘れていたのですが、特に急ぎなどではありませんが、こちらの Issue よければみておいていただけると嬉しいです (＞人＜ )✨ cc/ @yuki384

**Comment by yuki384** [comment]
![image](https://user-images.githubusercontent.com/31533303/85094376-9ddb0000-b229-11ea-8053-d3fbfb9f2c69.png)
デザイン案です💭

**Comment by yasulab** [comment]
> - A. Dojo に count カラム (Default: 1) を追加する
>    * 統計情報ページなどで `Dojo.count` を使っているはずなので、それらのコードを新カラムを使って計測するように書き換える

この方法でできそうかなーと思うので、ちょっと試しに実装してみます 🛠💨✨

**Comment by yasulab** [comment]
こちら草案の Pull Request を作ってみました! 😆🎉✨ 

:octocat: [連名で登録している道場もカウント可能にする #860](https://github.com/coderdojo-japan/coderdojo.jp/pull/860)
