### ISSUE TITLE
Dojo一覧でタグ/文章が長いとテキストが見切れてしまう問題

### ISSUE THREAD

**Issue by yuki384** [coderdojo-japan/coderdojo.jp#721]
# 現状
タグと文章が合計5行以上になったときに見切れてしまいます(＞A＜;

![image](https://user-images.githubusercontent.com/31533303/73617038-0d2acb80-465e-11ea-9cef-682eaa3fbcfe.png)
![image](https://user-images.githubusercontent.com/31533303/73617047-1caa1480-465e-11ea-9abc-b8a1ffced796.png)

# 解決策
dojo達が入っている親要素に`display: flex; flex-wrap;` を設定してあげて、
class="dojo"に
```CSS
display: block;
width: calc(50% - 10px); //50%というのは1行に2Dojoを表示させる場合。4つ表示させる場合は25%とか
height: auto;
```
と設定してあげると、行ごとに高さが揃うはずです。と同時にタグが6つ以上でも表示できるようになります。

試してないのでわからないので、あとで動作確認次第PRにします

**Comment by yasulab** [comment]
@yuki384 Issue ありがとうございます！

あれ、手元の実機だと再現できなかったのですが、どの端末で発生しましたか？📱👀💭

![6527512C-A016-4174-9665-A46DA6A56E85](https://user-images.githubusercontent.com/155807/73619026-afeb4600-466e-11ea-8609-a9fea6ddaf5d.jpeg)

**Comment by yuki384** [comment]
なぬ・・・？
MBP 2017 13inch でブラウザはChromeの最新版でした。
というか今iPhoneで確認したら再現できなかったので、もしかしたらブラウザの表示サイズの設定や拡張機能の影響など、私の環境がおかしいのかもしれません... 🤔

後で確認します

**Comment by Yuppymam** [comment]
私も確認してみました👀PCでは確認できませんでしたが、モバイルでは、たまみらDojo は見切れてしまっていました💦
![IMG_7F5040A7DF5E-1](https://user-images.githubusercontent.com/48109243/73632808-3d935980-46a0-11ea-8ca4-e4d732f69119.jpeg)

🔽5/SE では渋谷Dojoも見切れていそうです💦

<img width="347" alt="スクリーンショット 2020-02-03 16 15 58" src="https://user-images.githubusercontent.com/48109243/73632877-7c291400-46a0-11ea-8002-0b4bdef3d9ea.png">
<img width="364" alt="スクリーンショット 2020-02-03 16 16 17" src="https://user-images.githubusercontent.com/48109243/73632889-83e8b880-46a0-11ea-8cdc-bd4be5936ad3.png">

**Comment by yuki384** [comment]
確認できました、こちらiPhone8 Chromeですー！

![0AB66738-BF3C-4E31-9089-9146C106FD19](https://user-images.githubusercontent.com/31533303/73642982-09c32e80-46b6-11ea-8916-bfa9538d1822.jpeg)

**Comment by yasulab** [comment]
情報ありがとうございます！(＞人＜ ) 💖✨

手元に再現できる実機がないので、(もし可能なら) どなたか実機で確認できる方にお願いできると嬉しいです :sob: 😭 😭

**Comment by chicaco** [comment]
Android (SHARP AQUOS SH-04L) でも見切れていました。
![Screenshot_20200204-092818](https://user-images.githubusercontent.com/1582945/73702957-b393d100-4731-11ea-9bb3-b125dac08d7c.png)
![Screenshot_20200204-092846](https://user-images.githubusercontent.com/1582945/73702966-b8588500-4731-11ea-9f60-0ea63743013f.png)

**Comment by yuki384** [comment]
こちら修正してみました！
https://github.com/coderdojo-japan/coderdojo.jp/pull/728
