### ISSUE TITLE
CoderDojo 太宰府の変更依頼

### ISSUE THREAD

**Issue by MasatakaMiki** [coderdojo-japan/coderdojo.jp#729]
お世話になっています。
太宰府のチャンピオンの三木と申します。
以下、2点変更をお願いしたいのですが。

①ロゴを以下に変更お願いします。
https://drive.google.com/file/d/1txKwPgdwDKsy7afRgKHZKu9gWZBsCcRU/view?usp=sharing

②近日開催に太宰府も載せて欲しい。
https://coderdojo-dazaifu.connpass.com/

お手数おかけしますが、よろしくお願い申し上げます。
※issueをあげるより、変更してpull requestをした方がいいでしょうか？

**Comment by Yuppymam** [comment]
こちらで変更しておきますね🙆‍♀️✨
変更完了しましたら連絡しますので少々お待ちください😊

**Comment by Yuppymam** [comment]
ロゴ画像のところへアクセスしたところ権限がないと見れなさそうなので申請してみました🙇‍♀️
ご確認よろしくお願いします✨
