### ISSUE TITLE
Scrivito SDK を Rails から JavaScript に移せるかどうか調査する

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/coderdojo.jp#737]
Rails をアップグレードする際、基本的に Scrivito gem がボトルネックになっているので (大体半年〜１年以上のディレイがあるので)、Scrivito の SDK を Rails から JavaScript に切り替えられるかどうか調査したい。

cf. https://github.com/coderdojo-japan/coderdojo.jp/issues/736
cf. https://www.scrivito.com/release-notes
cf. https://www.scrivito.com/rails/release-notes

もし SDK を JavaScript に移行できれば、今後は Scrivito SDK と Rails のバージョンをそれぞれ別々にアップグレードできるようになるため、こちら側の都合の良いタイミングで Rails のアップグレードに取り掛かれそう :eyes: 💭 ✨ 

Latest Status: https://github.com/coderdojo-japan/coderdojo.jp/issues/736#issuecomment-1374709272

**Comment by nanophate** [comment]
https://github.com/coderdojo-japan/coderdojo.jp/pull/1268 https://github.com/coderdojo-japan/coderdojo.jp/pull/1506 で scrivito 関連の Gem を削除したので、クローズします。
