### ISSUE TITLE
近日開催の道場ページをアクセスしやすい配置にする/見せ方を考える

### ISSUE THREAD

**Issue by yuki384** [coderdojo-japan/coderdojo.jp#820]
https://coderdojo.jp/ から https://coderdojo.jp/events にリンクを飛ばす場所はここ(画像参照)
![image](https://user-images.githubusercontent.com/31533303/81652317-8496a500-946e-11ea-81a0-6879547a5565.png)

文章内の三文字のリンクのみ。
けれど、[近日開催の道場ページ](https://coderdojo.jp/events) のアクセス多め.

→ 見せ方を変えてUX改善できないか？

**Comment by yuki384** [comment]
- ヘッダーに追加したい💭
- ヘッダーがない🤔のでヘッダーを作ってからのほうが良さそう
- ヘッダー作成作業はここでやっていた(WIP) ぽい https://github.com/coderdojo-japan/coderdojo.jp/pull/515

**Comment by Yuppymam** [comment]
@yuki384 #515 めちゃくちゃ中途半端で終わっています💦
新たに作ってもらっても大丈夫です〜😂🙏✨

**Comment by yuki384** [comment]
書いていただいたヘッダーをもとに作ります！

**Comment by yasulab** [comment]
#843 のPR で対応されたので本 Issue は Close しちゃいますね 😉 ✨
対応ありがとうございました！！(＞人＜ )💖
