### ISSUE TITLE
横幅が大きいときに灰色の背景色が出てしまう問題を修正したい

### ISSUE THREAD

**Issue by yuki384** [coderdojo-japan/coderdojo.jp#845]
## 現状
![image](https://user-images.githubusercontent.com/31533303/83998885-8afc3c00-a99c-11ea-9bb5-a1b7295f4350.png)

> 同じ画像を拡大&ぼかし&暗めの効果入れて背景に表示…とかどうでしょう 

by yuki384

**Comment by yasulab** [comment]
Issue 作成ありがとうございます！(＞人＜ )✨
