### ISSUE TITLE
📮 お問い合わせフォームにpaddingをつける

### ISSUE THREAD

**Issue by yuki384** [coderdojo-japan/coderdojo.jp#887]
お問い合わせフォームに入力する際に、余白が足りず、キャレット(入力する場所を示すチカチカする縦線)が見えなくなってしまうので修正したい。
![image](https://user-images.githubusercontent.com/31533303/87242540-91347b00-c468-11ea-9103-13a1fd4ee2de.png)

**Comment by yasulab** [comment]
確かに...!! (๑•̀ㅂ•́)و✨

フォームには Wufoo を使っているので 1Password でログインし、CSS をいじる必要がありそうです！

**Comment by yasulab** [comment]
お、こちら調べてみたら CSS は https://coderdojo.jp/css/wufoo.css を参照しているようだったので、こちら当該ファイルを修正するといけそうでした 👀💨✨

**Comment by yasulab** [comment]
Fixed by https://github.com/coderdojo-japan/coderdojo.jp/commit/cf6347da9d4a4be5e3ea52853ca581fa6d76d4db
Thanks...!! 💖✨
